### ISSUE TITLE
How/why do backends contain sensitive data?

### ISSUE THREAD

**Issue by glenjamin** [helm/helm-www#1003]
In the section on storage backends
https://github.com/helm/helm-www/blob/master/content/en/docs/topics/advanced.md#storage-backends

There is the following warning
> **PRODUCTION NOTES:** The release information might contain sensitive data (like passwords, private keys, and other credentials) that needs to be protected from unauthorized access.

However it is unclear _why_ the release information might contain sensitive data. Is this because it stores the contents of charts and values files, and those could contain anything, or is it for some other reason?

The reason for this question is that I'm wanting to allow people to use a `read` access RBAC role for normal operations, but elevate to `edit` only when needed, and currently `edit` is required to do what feel like they should be safe operations like `helm list`, because the default backend is a secret and secrets cannot be read from a `read` role.

**Comment by bacongobbler** [comment]
Your assumption about charts and values being stored in the release metadata is correct.

You can create a separate role for reading secrets, but for obvious reasons that is not provided in the default read role. I believe the documentation describes how to create such a “secret-reader” role if desired.

keep in mind that read access does provide those users access to chart values and manifests, which can contain sensitive information. So use at your own risk.

**Comment by bacongobbler** [comment]
https://github.com/helm/helm-www/blob/master/content/en/docs/topics/rbac.md

**Comment by glenjamin** [comment]
Ok, thanks - I'll send a PR tomorrow which expands the docs a little bit with this clarification

**Comment by glenjamin** [comment]
Would it be possible to split apart the storage of the sensitive and non-sensitive parts of helm's data? I can open an issue for that in the right place if it's something that might be considered.

Right now it feels awkward that I require `read` access to secrets in order to run simple commands like `helm list`, `helm history` or `helm status`.

**Comment by bridgetkromhout** [comment]
Hi, @glenjamin - thanks for your PR to clarify the docs; I've merged it, which closed this issue. If you'd like to propose discussion about splitting the way data is stored, https://github.com/helm/helm/issues/new is a good place for that. Thanks!
