### ISSUE TITLE
helm install example uses a racially loaded term

### ISSUE THREAD

**Issue by dwj300** [helm/helm-www#1007]
The [Using Helm](https://helm.sh/docs/intro/using_helm/#helm-install-installing-a-package) docs (which are excellent!) use an example of installing `stable/mariadb` for `helm install` which reference a master and slave, which are racially loaded terms. The chart should be fixed as well (and I plan to submit an issue upstream), but in the mean time could the helm community consider using a different chart in this example? Preferably one without any loaded terms?

**Comment by bridgetkromhout** [comment]
Thanks, @dwj300! Please do submit issues and PRs for any other necessary updates, and we'll keep improving together.
