### ISSUE TITLE
Host chartmuseum.com?

### ISSUE THREAD

**Issue by jdolitsky** [helm/helm-www#1015]
The source for chartmuseum.com is located here: https://github.com/chartmuseum/www

That domain name is owned by me and DNS configured in a personal account. Can we get this transferred to wherever helm.sh lives, and also follow the same release process as helm-www? It is also a hugo site

cc @bridgetkromhout

**Comment by bridgetkromhout** [comment]
Thanks, @jdolitsky! This sounds like a useful plan that we will follow up on.

**Comment by caniszczyk** [comment]
@jdolitsky can we transfer the domain over to CNCF and to our netlify group?

**Comment by jdolitsky** [comment]
@caniszczyk - yes, happy to do so. I can unlock it and provide transfer code etc.

**Comment by jdolitsky** [comment]
This has been successfully transferred and hosted in the Helm Netlify account! https://chartmuseum.com/
