### ISSUE TITLE
[ja] menu climbs out

### ISSUE THREAD

**Issue by FlymeDllVa** [helm/helm-www#1032]
Safari 3072 × 1920
<img width="1785" alt="Снимок экрана 2021-02-28 в 12 41 56" src="https://user-images.githubusercontent.com/33265875/109414139-5add4900-79c2-11eb-82e2-6f9c8c837cb4.png">

**Comment by tastypackets** [comment]
Similar issue on FireFox, but it's appears to be effected by the viewport size. Reducing the horizontal size of viewport eventually gets it back in line. This image is taken on 1440p.
![image](https://user-images.githubusercontent.com/20361796/110724573-a15d4f80-81db-11eb-869e-2845e91518b0.png)
