### ISSUE TITLE
New helm plugin - official doc

### ISSUE THREAD

**Issue by HamzaZo** [helm/helm-www#1079]
Hello!
I create a new helm v3 plugin to help the community to fetch values from an older release.  [helm-val](https://github.com/HamzaZo/helm-val)

I would like to know what are the criteria to add a plugin to the official [documentation](https://helm.sh/docs/community/related/#helm-plugins)?

Thanks

**Comment by bacongobbler** [comment]
transferred to helm-www.

**Comment by HamzaZo** [comment]
Thanks @bacongobbler for your answer

**Comment by bridgetkromhout** [comment]
Thanks, @HamzaZo!
