### ISSUE TITLE
Outdated docs about directory name constraint

### ISSUE THREAD

**Issue by SimonAlling** [helm/helm-www#1086]
Under [Best Practices / General Conventions / Chart Names](https://helm.sh/docs/chart_best_practices/conventions/#chart-names), this constraint on chart directory names is described:

> The directory that contains a chart MUST have the same name as the chart. Thus, the chart `nginx-lego` MUST be created in a directory called `nginx-lego/`. This is not merely a stylistic detail, but a requirement of the Helm Chart format.

However, it was removed in https://github.com/helm/helm/pull/4141, so I believe the documentation source [here](https://github.com/helm/helm-www/blob/2875cecd9b1b8b6290e9fee595e288807f033eb5/content/en/docs/chart_best_practices/conventions.md#chart-names) needs to be updated.

**Comment by bridgetkromhout** [comment]
Hi, @SimonAlling! Thanks; you are correct. Would you like to submit a PR to change this documentation? Appreciated.

**Comment by SimonAlling** [comment]
Yes, I would. I'll give it a shot as soon as I have time.
