### ISSUE TITLE
Docs: i18n menu is broken in nav-fixed.html

### ISSUE THREAD

**Issue by svityashchuk** [helm/helm-www#1091]
There is an issue with language switcher when on scroll.
The `nav-fixed.html` template is displayed when page scrolled down.
And in that template few lines was commented in PR #1074 . I suppose that was done for testing purposes and just needs to be uncommented.

![image](https://user-images.githubusercontent.com/11519148/117318115-ccd68080-ae92-11eb-81eb-c785896fbadc.png)

**Comment by flynnduism** [comment]
Thanks @svityashchuk - I will correct this!

**Comment by bacongobbler** [comment]
fixed in #1092.
