### ISSUE TITLE
Update website to follow CNCF guidelines

### ISSUE THREAD

**Issue by mattfarina** [helm/helm-www#112]
See https://www.cncf.io/projects/website-guidelines/ for more detail

**Comment by bacongobbler** [comment]
From looking at the points, it appears this may be the only change necessary to be compliant with those guidelines:

> CNCF requests that graduated and incubating projects include the sentence “We are a Cloud Native Computing Foundation project.” and the CNCF logo near the bottom of their project homepage. Inception-level projects should include the sentence “We are a Cloud Native Computing Foundation inception project.” and the CNCF logo. We also appreciate a link to KubeCon + CloudNativeCon as the events approach.

Are there other guidelines you see on there that needs addressing?

**Comment by idvoretskyi** [comment]
@bacongobbler yes, that should be enough.
