### ISSUE TITLE
Common Helm Helper Chart point to archived

### ISSUE THREAD

**Issue by AssafKatz3** [helm/helm-www#1122]
Hi,

The [section](https://helm.sh/docs/topics/library_charts/#the-common-helm-helper-chart) point to [incubator](https://github.com/helm/charts/tree/master/incubator/common) which it was archived. I have no idea to where (if any) it was moved.

Thanks

**Comment by hickeyma** [comment]
@AssafKatz3 That chart is still in the repo but the repo is now deprecated and no longer maintained. You can pull down the chart using `helm pull` command and use it.

Thanks for raising this @AssafKatz3 as I think we should update this section to mentioned that the repo is now deprecated archived.
