### ISSUE TITLE
Tutorial uses a wrong key value pair in the manifest for configmaps.

### ISSUE THREAD

**Issue by AahanSingh** [helm/helm-www#1123]
Hi,
While trying out the tutorial on the following sections:
- https://helm.sh/docs/chart_template_guide/control_structures/#ifelse
- https://helm.sh/docs/chart_template_guide/control_structures/#controlling-whitespace

the configmap has the key value pair `mug: true`. Running with `helm install --dry-run --debug ./mychart` there is no problem but without the `--dry-run --debug` flags, kubernetes throws an error since the value assigned to mug isnt a string. 

Was there a specific reason why the tutorial was created with `mug: true` rather than `mug: "true"` ? I suspect it could have been done this way to show that even though the `helm install` command works with the `--dry-run --debug` flags it wont without them. Either way there are one of 2 things we could do here:

- add a small section stating that the command wont work on the cluster 
- change `mug: true` to `mug: "true"`

so that less informed people who run the install command without those flags wont get stuck figuring out whether the issue is because they made a mistake with the if else construct or because of a wrong manifest because this is such a minute detail. 
Took me a good hour to figure this out haha :-D.

**Comment by AahanSingh** [comment]
I have created the PR here https://github.com/helm/helm-www/pull/1124

**Comment by AahanSingh** [comment]
Hi @mattfarina could someone be appointed to merge the pull request?

**Comment by bridgetkromhout** [comment]
Hi, @AahanSingh - thanks for your PR! Merged.
