### ISSUE TITLE
chart archives not supported without repo

### ISSUE THREAD

**Issue by mattfarina** [helm/helm-www#1157]
In the docs at https://helm.sh/docs/topics/charts/#managing-dependencies-manually-via-the-charts-directory it says you can use a chart directory or archive for those in the charts directory without a repo being specified. This is an error. You can only have a directory and not a chart archive. The docs need to be corrected.

**Comment by bridgetkromhout** [comment]
Resolved in https://github.com/helm/helm-www/pull/1168
