### ISSUE TITLE
quickstart 404

### ISSUE THREAD

**Issue by fansi404** [helm/helm-www#1192]
[quickstart](https://helm.sh/zh/docs/topics/quickstart/) link in page [chart_repository](https://helm.sh/zh/docs/topics/chart_repository/) 404

![image](https://user-images.githubusercontent.com/89375976/132501657-cea9f4b4-8226-4f5d-a0a2-4d4fcfcce5ce.png)

**Comment by flynnduism** [comment]
Closed via #1193
