### ISSUE TITLE
Helm is an incubating project of CNCF (not inception)

### ISSUE THREAD

**Issue by idvoretskyi** [helm/helm-www#120]
https://github.com/helm/helm-www/pull/118 mentions Helm as CNCF inception project, which is an incorrect statement ("inception" is the old name of "sandbox").

The correct statement is "We are a Cloud Native Computing Foundation incubating project."

**Comment by flynnduism** [comment]
Thanks @idvoretskyi - I pasted incorrect text into the PR, what the site now says is:

> We are a Cloud Native Computing Foundation project.

I can add text to specify "incubating" if required.

**Comment by dankohn** [comment]
We’d prefer incubating but either is fine.

**Comment by flynnduism** [comment]
Closed via #121
