### ISSUE TITLE
Should `main` branch be used in install docs?

### ISSUE THREAD

**Issue by bertdeblock** [helm/helm-www#1204]
Hi, I was wondering if the `main` branch should be used [here](https://helm.sh/docs/intro/install/#from-script) instead of the `master` branch?

**Comment by bacongobbler** [comment]
Yes, good catch. Feel like contributing a PR?

**Comment by bertdeblock** [comment]
Sure! I'll see if I can get the docs up and running locally. Should this be changed manually for each language or is this something that can be updated in a config file? (Sorry I'm not really familiar with this repo and helm itself).
