### ISSUE TITLE
Translation suggestions

### ISSUE THREAD

**Issue by zeaone** [helm/helm-www#1207]
the url is here：[https://helm.sh/zh/docs/chart_template_guide/yaml_techniques/](https://helm.sh/zh/docs/chart_template_guide/yaml_techniques/#%E6%8E%A7%E5%88%B6%E5%A4%9A%E8%A1%8C%E5%AD%97%E7%AC%A6%E4%B8%B2%E4%B8%AD%E7%9A%84%E7%A9%BA%E6%A0%BC)

the raw translation is **文本块中的缩进会被保留，也会保留行跳出的结果：**

I think this sentence should be translated as: **文本块中的缩进会被保留，也会保留换行符：**

**Comment by bridgetkromhout** [comment]
Thanks!
