### ISSUE TITLE
Helm push command missing documentation

### ISSUE THREAD

**Issue by aphilippejolivel** [helm/helm-www#1210]
Hello guys,

It seems that the Helm Push command does not have a documentation page. Especially with the new 3.7.0 syntax it would be great to have one.

I couldn't find trace of it even in prior versions (as helm chart push) as a seperate page, it does appear in https://helm.sh/docs/topics/registries/ though

Is it by design ?

Thanks,
Axel

**Comment by bridgetkromhout** [comment]
Hi, @aphilippejolivel - the updates you were asking about came after you opened this issue, in https://github.com/helm/helm-www/pull/1228. There are now more details for `helm push` at https://helm.sh/docs/topics/registries/#commands-for-working-with-registries, and the CLI documentation is available at https://helm.sh/docs/helm/helm_push/. Please let us know if you can point to other places that you'd expect more details. Thanks!

**Comment by aphilippejolivel** [comment]
Thanks, looks great ! I'll check with my team if they're seeing small improvements that could be made.

Thanks for the work.
