### ISSUE TITLE
[zh]It is not appropriate to translate "Helm Chart" into "Helm 图表"

### ISSUE THREAD

**Issue by vinnyzhaowenyu** [helm/helm-www#1235]
**Chart** 直接翻译成中文的意思是：`图表，曲线图；海图，星位图；排行榜`等意思。但这一些翻译都不能表示 **Chart** 的核心功能，反而让使用者更加的困惑。

类似的 **Helm**直接翻译成中文表示：`舵；舵柄；领导地位；驾驶盘`一样，直接翻译并不合适。反而直接使用英文的 `Helm` 更便于沟通交流。

建议考虑将 `Helm` ,`Helm Chart` 作为专有名称，不进行翻译，保留英文词语。 

----

**Chart** , The direct translation into Chinese means `图表，曲线图；海图，星位图`.  However, none of these translations can express the core function of Chart, which makes users more confused.

The similar Helm translates directly into Chinese: `舵；舵柄；领导地位；驾驶盘` direct translation is not appropriate. On the contrary, using `Helm` in English is more convenient for communication.

It is suggested to consider `Helm` and `Helm Chart` as proper names without translation and keep English words.

**Comment by vinnyzhaowenyu** [comment]
fix  https://github.com/helm/helm-www/pull/1236

**Comment by bridgetkromhout** [comment]
Thank you, @vinnyzhaowenyu!

I would like to hear from @Zhanxueyou who has done a lot of the Chinese translation, in case they have an opinion. Thanks.

**Comment by Zhanxueyou** [comment]
> Thank you, @vinnyzhaowenyu!
> 
> I would like to hear from @Zhanxueyou who has done a lot of the Chinese translation, in case they have an opinion. Thanks.

@bridgetkromhout We will consider to translate Proprietary Vocabulary more appropriately later. Thanks.

**Comment by Zhanxueyou** [comment]
@vinnyzhaowenyu 可以的，有更合适的翻译再考虑
