### ISSUE TITLE
Blog background/text isn't really readable 

### ISSUE THREAD

**Issue by rimusz** [helm/helm-www#124]
Can we use the same styling for the blog as per rest of the site, as that dark blue background with the the white text is not nice for the eyes.

the current blog:
<img width="964" alt="screenshot 2018-07-24 12 29 24" src="https://user-images.githubusercontent.com/5215395/43135547-aa97cff0-8f3d-11e8-9796-80082906bbb4.png">
vs the rest of the site:
<img width="914" alt="screenshot 2018-07-24 12 20 11" src="https://user-images.githubusercontent.com/5215395/43135552-b177ed28-8f3d-11e8-935e-c3b66a2e0998.png">

**Comment by bacongobbler** [comment]
cross-posting from https://github.com/helm/helm-www/issues/153#issuecomment-467597423:

> I believe this and #124 may have been resolved in #162 (looking at https://helm.sh/blog/2018-09-25-chart-testing-intro/ for example).

Let's close this in favour of #153 to keep the discussion going in one ticket. Thanks!
