### ISSUE TITLE
Want to change a text

### ISSUE THREAD

**Issue by rounaksarda** [helm/helm-www#1251]
On link:  "https://helm.sh/docs/intro/quickstart/#initialize-a-helm-chart-repository"

Original line:  **"Once this is installed, you will be able to list the charts you can install:"**

It should be either: "Once Helm is installed, you will be able to list the charts you can install:"
Or : "Once this chart repository is added, you will be able to list the charts you can install:"

**Comment by angellk** [comment]
thanks @rounaksarda - your second option makes more sense. feel free to submit a PR to change it!
