### ISSUE TITLE
Translation suggestions

### ISSUE THREAD

**Issue by zeaone** [helm/helm-www#1252]
the url is here：[url](https://helm.sh/zh/docs/chart_template_guide/yaml_techniques/#%E6%8A%98%E5%8F%A0%E5%A4%9A%E8%A1%8C%E5%AD%97%E7%AC%A6%E4%B8%B2)

the raw translation is 有时需要在YAML中表示多行字符串，但是被解释时被当做单行字符串

I think this sentence should be translated as: 有时您想在 YAML 中用多行表示一个字符串，但希望在解释时将其视为一个长行。

**Comment by bridgetkromhout** [comment]
Thank you!
