### ISSUE TITLE
Add guidance/guidelines for distributed charts hub

### ISSUE THREAD

**Issue by scottrigby** [helm/helm-www#1260]
## Current status

The goal of me moving this issue is to be able to archive the helm/charts repo and make sure that the work started/pinned here makes its way into helm.sh/docs.

## Original issue

Now that we're moving charts to distributed Helm repos to be listed on the Hub, people need some guidance

**Comment by angellk** [comment]
Closing as stale, please open a new issue if this is still needed @scottrigby
