### ISSUE TITLE
[zh]Kubernetes Distribution Guide translation suggestions

### ISSUE THREAD

**Issue by zeaone** [helm/helm-www#1268]
the url is here：https://helm.sh/zh/docs/topics/kubernetes_distros/

the raw translation is :Helm 应该与任何 Kubernetes的一致性版本一起工作 （不管 认证与否）。

I think this sentence should be translated as: Helm 应该适用于任何符合标准的 Kubernetes 版本（无论是否经过认证）。

**Comment by karenhchu** [comment]
Thank you!
