### ISSUE TITLE
Links under the "Using Helm" section are broken

### ISSUE THREAD

**Issue by simonft** [helm/helm-www#128]
I'm seeing the same behavior described in #51. Clicking any of the links under "Using Helm" (like https://docs.helm.sh/using_helm/#quickstart-guide ) results in the browser loading a page with the header "Using Helm" but none of the expected information.

**Comment by simonft** [comment]
This started working a couple minutes after submitting. Apologies for the noise.

**Comment by flynnduism** [comment]
No problem @simonft, appreciate the flag regardless.
