### ISSUE TITLE
sidebar navigation does not scroll

### ISSUE THREAD

**Issue by bacongobbler** [helm/helm-www#130]
This is especially a concern when you expand the "Helm Commands" nav button as it consumes the majority of the nav bar. Scrolling down on the main docs page does not help.

**Comment by flynnduism** [comment]
Working on this issue currently.

**Comment by bacongobbler** [comment]
closed via #4428. Changes are still rolling out but should be available at some time in the future.

**Comment by flynnduism** [comment]
Changes are live on [docs.helm.sh](https://docs.helm.sh)
