### ISSUE TITLE
Broken link on plugins guide

### ISSUE THREAD

**Issue by robertomlsoares** [helm/helm-www#131]
There is a broken link here: https://docs.helm.sh/using_helm/#the-helm-plugins-guide

'Existing plugins can be found on [related](https://docs.helm.sh/using_helm/related.md#helm-plugins) section or by searching Github'

Related is linking to https://docs.helm.sh/using_helm/related.md#helm-plugins

**Comment by flynnduism** [comment]
Thanks Robert. Link should be [https://docs.helm.sh/related/#helm-plugins](https://docs.helm.sh/related/#helm-plugins). Will update.

**Comment by bacongobbler** [comment]
closed via #168
