### ISSUE TITLE
Request to join https://github.com/helm/helm-www

### ISSUE THREAD

**Issue by yxxhero** [helm/helm-www#1321]
Hello everyone, I apply to join https://github.com/helm/helm-www , in order to contribute to the document, especially Chinese, I hope to get your support. My GitHub: https://github.com/yxxhero.  Thanks very much.

@bacongobbler @mattfarina @bridgetkromhout @hickeyma @scottrigby

**Comment by yxxhero** [comment]
@bacongobbler @mattfarina @bridgetkromhout @hickeyma @scottrigby ping

**Comment by karenhchu** [comment]
hello @yxxhero – are you still interested? If so, I will work on gathering the votes. On a related note, we have some a PR for traditional Chinese docs – is this something you would also be able to help review? If not, no worries.

**Comment by yxxhero** [comment]
Yes. Thanks very much. @karenhchu looking forward to join.

**Comment by yxxhero** [comment]
@karenhchu if need me to do anything. Please contact me.

**Comment by yxxhero** [comment]
@karenhchu ping

**Comment by karenhchu** [comment]
Apologies for the delay – I called the vote and will update here when I get responses.

**Comment by yxxhero** [comment]
@karenhchu Thanks very much.

**Comment by karenhchu** [comment]
The necessary votes are in. The PR to add you as a maintainer is now open.

**Comment by yxxhero** [comment]
@karenhchu Thanks very much. It's my pleasure.

**Comment by karenhchu** [comment]
Hooray! You're now a maintainer of the helm-www repo. Looking forward to working with you! 🎉
