### ISSUE TITLE
Minor fix in the document - Helm upgrade as oppose to Helm update

### ISSUE THREAD

**Issue by JTG2020** [helm/helm-www#1322]
I am referring to the contents of link - https://helm.sh/docs/chart_template_guide/functions_and_pipelines/

Below text mentioned helm commands and there is no helm update...i think it should be helm **_upgrade_**.

Keep in mind that Helm is not supposed to contact the Kubernetes API Server during a helm template or a helm install|**_update_**|delete|rollback --dry-run, so the lookup function will return an empty list (i.e. dict) in such a case.
I can fix that quickly if allowed.

**Comment by hickeyma** [comment]
@JTG2020 Go for it
