### ISSUE TITLE
Some page order of Chinese docs is wrong

### ISSUE THREAD

**Issue by Dongzhenpu** [helm/helm-www#1327]
Hi there, 
I found that there are one [page](https://helm.sh/zh/docs/chart_template_guide/notes_files/)'s order is wrong in Chinese docs, but I didn't find where to modify this. So I make a issue instead of a PR. 
This page should between [accessing_files](https://helm.sh/zh/docs/chart_template_guide/accessing_files/) and [subcharts_and_globals](https://helm.sh/zh/docs/chart_template_guide/subcharts_and_globals/).
Can someone correct this or tell me how can I modify this order in github repo?

**Comment by bacongobbler** [comment]
Each page has a weight. See line 4 on https://github.com/helm/helm-www/blob/main/content/zh/docs/chart_template_guide/accessing_files.md. You can change the value of that weight to influence the order.

**Comment by Dongzhenpu** [comment]
Thanks!
