### ISSUE TITLE
Bot to check blog posts have a /blog/ in url

### ISSUE THREAD

**Issue by mattfarina** [helm/helm-www#135]
Some of the blog posts are off the root of the helm.sh site. Others are under blog. We need to be consistent and likely need a check to make sure we have it that way.

I propose we add a check that enforces a blog post have a prefix of `/blog/`.

**Comment by bridgetkromhout** [comment]
Looking at https://helm.sh/blog/ now, it doesn't appear this is still the case for existing posts. Do we think further action needs to be taken? Thanks.

**Comment by bacongobbler** [comment]
looks like this can be closed. Thanks for the fixes @bridgetkromhout :)
