### ISSUE TITLE
testable documentation

### ISSUE THREAD

**Issue by phil9909** [helm/helm-www#1389]
Background: Recently, we found a discrepancy between the documented behavior and the actual behavior of Helm (https://github.com/helm/helm/issues/11518). Such cases could be limited by having "testable documentation".

I know that istio is doing this: https://github.com/istio/istio.io/blob/master/tests/README.md

In essence: They have a test framework that extracts any code examples from the markdown and makes them available to the test cases. The test cases will e.g. apply the example resource to a Kubernetes cluster and verify that it does the expected (documented) thing.
IMHO their tests are quite hard to read, partially because they are written in `bash` I guess. But I like the general idea of extracting defined snippets from the documentation and actually running them.

WDYT?

Would you accept something like this as a contribution?

**Comment by angellk** [comment]
Absolutely - that sounds like a great contribution. Would you like to try it on a page and it can be reviewed?

**Comment by angellk** [comment]
if you are still interested, please describe in a HIP: https://github.com/helm/community/blob/main/hips/hip-0001.md
