### ISSUE TITLE
I  hope  helm  can  install kubevirt use  only  one  command install  & config

### ISSUE THREAD

**Issue by summer-father** [helm/helm-www#1405]
I  hope  helm  can  install kubevirt   only  one  command
https://kubevirt.io
it  will  be  a greate  thing  in  the  futrue

**Comment by probyte12** [comment]
The [Linux commands](https://www.probyte.org/linux-commands/) covered in this lesson will assist you as you use Linux. The 50+ Linux commands you need to know are listed at ProByte. Visit our website right now to learn more.

**Comment by angellk** [comment]
@summer-father - that would be great! if you have ideas on how this could be implemented, please describe it in a HIP: https://github.com/helm/community/blob/main/hips/hip-0001.md
