### ISSUE TITLE
<!DOCTYPE html> <html Lang= "es"> <head> <meta = "geo-localización-data" data-geo-eu= "geo-noteFeu" data-geo-contry -code="co"data-geo -afs-international ><Script type =text/javascript,>> /* global name = name \\ [ ];type =  "text/javascript" src  ="http.js" ></script><meta  charr set = UTF-8"/>

### ISSUE THREAD

**Issue by Juanbh89106** [helm/helm-www#1454]

**Comment by Juanbh89106** [comment]
<! html>; ><, C++ (...) Hola,  si. Ya lo había visto, en EEUU hay unas élites, con poder económico y político que se resisten a los cambios,  no están solos porqué tienen base social, son problemas sociales que se resistencia a desaparecer,  igual alegan el derecho a ir armados, a la existencia de  un Dios omnipotente y sobre todo se proclaman cómo el alguacil mundial.  Esas élites tienen posiciones importantes en el Estado y su organización política.
Así las casas. El mundo, la naturaleza existente, el medio ambiente que conocemos,  nos acaba de decir: los recursos naturales no son eternos, la vida se está agotando. Por la injerencia de la economía en la producción, el hombre no fue capaz de establecer un equilibrio en la explotación de los recursos y la supervivencia humana,  y la crisis de la pandemia nos demostró,  estamos llenos de cosas que no necesitamos para vivir,  perseguimos un ideal de  sujetos que es vacío por dentro y no hay nada que lo complazca, debemos de buscar un sentido a ser interno que llevamos dentro; por último todo no seguirá siendo igual y tiene que cambiar. 
El orden mundial en estos momentos se está definiendo en una guerra. Si somos contundentes, si sabemos que nos conviene como generación vamos a poder sobrevivir y de eso depende nuestro futuro. 
Se tienen que dar transformaciones que incluyan o todos los sujetos respetando la diversidad humana.
No pueden estar consolidadas las economías en una figura como la que existe hoy.
Las herramientas virtuales  la información y cómo se apliquen las tecnologías en el diario vivir y lo que hacemos es determinante en las nuevas relaciones de producción que se van a establecer en el futuro que se está forjando, el medio ambiente es fundamental para poder pensar hacia adelante y según lo que se defina para el futuro va  a determinar cuánto va a estar la especie humana en el mundo que se conoce hoy.
C/*; ><//>;

**Comment by angellk** [comment]
@Juanbh89106 if you are trying to contribute, please review the contribution guidelines! https://github.com/helm/helm-www#contributing
