### ISSUE TITLE
link to k8s service account permission results in 404 in https://helm.sh/docs/topics/rbac/

### ISSUE THREAD

**Issue by prembhaskal** [helm/helm-www#1465]
Hi,
On this page https://helm.sh/docs/topics/rbac/ the link to k8s service-accounts https://kubernetes.io/docs/admin/authorization/rbac/#service-account-permissions results in 404. It should be changed to https://kubernetes.io/docs/reference/access-authn-authz/rbac/#service-account-permissions .

**Comment by yxxhero** [comment]
@prembhaskal merged. so close the issue. thanks for your PR.
