### ISSUE TITLE
Documentation of `helm install --dry-run` does not match the actual behaviour

### ISSUE THREAD

**Issue by MaxKlotz** [helm/helm-www#1469]
The docs for [Debugging Templates](https://helm.sh/docs/chart_template_guide/debugging/) it says

    helm install --dry-run --debug: We've seen this trick already. It's a great way to have the server render your templates, then return the resulting manifest file.

This documentation misleading, because--dry-run does not contact the server.
Explained in issue https://github.com/helm/helm/issues/12031

**Comment by OneCricketeer** [comment]
Seems related to changes in #1522
