### ISSUE TITLE
[helm.sh] blog needs additional styling

### ISSUE THREAD

**Issue by flynnduism** [helm/helm-www#153]
Code blocks need some ❤️ on the blog. `code` and `pre` tags need styles to add padding, adjust sizing, shading etc.

Screenshots:

<img width="854" alt="screen shot 2018-11-15 at 1 00 14 pm" src="https://user-images.githubusercontent.com/686194/48581440-ac876580-e8d6-11e8-93ee-f4b3bfa1c110.png">

<img width="1024" alt="screen shot 2018-11-15 at 1 00 25 pm" src="https://user-images.githubusercontent.com/686194/48581450-b1e4b000-e8d6-11e8-8672-d4f9ac86b43b.png">

---

This is related to #124 - I'd like to spend some time cleaning up the blog layout for a better reading experience (invert colors to dark text on white background).

**Comment by bridgetkromhout** [comment]
I believe this and #124 may have been resolved in https://github.com/helm/helm-www/pull/162 (looking at https://helm.sh/blog/2018-09-25-chart-testing-intro/ for example).

**Comment by flynnduism** [comment]
Yeah now the styles have been updated for better code formatting, I'm going to mark this closed
