### ISSUE TITLE
Broken links in docs

### ISSUE THREAD

**Issue by a-robinson** [helm/helm-www#161]
At least two of the links in the docs that are meant to take you to the RBAC portions of the docs are broken on the live docs site. In particular:

1. The link to "Tiller and Role-Based Access Control" from this section https://docs.helm.sh/using_helm/#special-note-for-rbac-users
2. The link to "RBAC enabled clusters" from https://docs.helm.sh/using_helm/#easy-in-cluster-installation

I'd fix the links myself, but it's not actually clear to me what's wrong with the first one judging by how other section references work in your docs. It seems likely that they're both trying to reference https://docs.helm.sh/using_helm/#role-based-access-control, though.

**Comment by bacongobbler** [comment]
closed via #168
