### ISSUE TITLE
Plugin: Helm-tui a terminal UI for Helm

### ISSUE THREAD

**Issue by pidanou** [helm/helm-www#1668]
Hi guys,

I have been working on this small project to have a terminal UI for Helm. Its aime is to to have a simple way to manage you helm assets.
It might be good enough right now but some more usage and tests would be great.
Any suggestion would be greatly appreciated.
If everything works correctly I'll be very happy to share it on the website.
[https://github.com/pidanou/helm-tui](https://github.com/pidanou/helm-tui)

Thank you!

**Comment by yxxhero** [comment]
@pidanou welcome for PRs.
