### ISSUE TITLE
Doc links are broken

### ISSUE THREAD

**Issue by enrmarc** [helm/helm-www#181]
Example: https://helm.sh/docs/helm/helm_upgrade/

**Comment by bweston92** [comment]
Here are a few broken links too I cannot see where to update. https://helm.sh/docs/helm/#see-also

**Comment by enrmarc** [comment]
@bacongobbler 
- Via Google search (keywords `helm upgrade`). It's the second entry
- In https://helm.sh/docs/helm/#see-also

**Comment by flynnduism** [comment]
Thanks for clarifying @bweston92 and @enrmarc - working on a fix for this now.

Indeed the _see also_ links for each of the Helm Commands require the addition of a `/docs` prefix.

**Comment by flynnduism** [comment]
Fix for this has shipped, links in that section corrected: [https://helm.sh/docs/helm/#helm](https://helm.sh/docs/helm/#helm)
