### ISSUE TITLE
Helm website documentation not up to date

### ISSUE THREAD

**Issue by thomasLeclaire** [helm/helm-www#185]
On the main doc webpage https://helm.sh/docs/using_helm, it sounds like at least the first links are broken :
https://helm.sh/docs/using_helm/#installing-helm
https://helm.sh/docs/using_helm/#quickstart

doc sounds to be correct on github side : https://github.com/helm/helm/blob/master/docs/using_helm.md

initially wrongly opened here for info : https://github.com/helm/helm/issues/5376

**Comment by flynnduism** [comment]
Reviewing the docs, is seems that the Using Helm section hasn't properly generated. Clearing cache and rebuilding the site has restored the proper content:

https://helm.sh/docs/using_helm/#quickstart
https://helm.sh/docs/using_helm/#installing-helm

Thanks for flagging this - it's resolved for now. I'll investigate why this occurred.
