### ISSUE TITLE
Add rss or atom feed

### ISSUE THREAD

**Issue by levlaz** [helm/helm-www#187]
I wasn't able to find a feed for the helm blog, I'd love to keep up with posts. Am I missing something or does this not exist yet?

**Comment by flynnduism** [comment]
There is a blog feed available at [https://helm.sh/blog/index.xml](https://helm.sh/blog/index.xml) - but you raise a good point it's not accessible. I think the blog layouts need the addition of a feed link someplace.

I'll add this.

**Comment by levlaz** [comment]
Thank you very much for the link! It’s good enough for me, but making this more discoverable would be great for the 7 of us who still use a feed reader. :)

**Comment by rubenv** [comment]
Please just add a link to the RSS feed, if not just a meta tag:

```
<link href="https://helm.sh/blog/index.xml" rel="alternate" type="application/rss+xml" title="Helm" />
```

It's such a shame that I have to come to Github Issues to find the feed.

**Comment by flynnduism** [comment]
Site updated with accessible RSS feed links on the blog. This issue is marked closed.

Thanks for your feedback - this helps improve the project!

**Comment by rubenv** [comment]
Thanks! Sadly, in this day and age, RSS needs all the help it can get.
