### ISSUE TITLE
Some Helm TOC links broken

### ISSUE THREAD

**Issue by elsmorian** [helm/helm-www#190]
Just going through the Table of Contents links here https://helm.sh/docs/chart_best_practices/ the anchors for some links are broken from that TOC - clicking them doesn't take you to the correct section of the page. Looking at the docs in GitHub, it looks like the ones are broken are where the markdown filenames do not match the link text, and I guess whatever is building the HTML docs from the Markdown can’t build the links?

The Following links are broken:
https://helm.sh/docs/chart_best_practices/#conventions
https://helm.sh/docs/chart_best_practices/#requirements
https://helm.sh/docs/chart_best_practices/#labels
https://helm.sh/docs/chart_best_practices/#pods
https://helm.sh/docs/chart_best_practices/#custom_resource_definitions

**Comment by elsmorian** [comment]
(I looked at submitting a PR, but not 100% what the issue is and couldn't quite work out how the docs are built, sorry!)

**Comment by flynnduism** [comment]
Thanks @elsmorian, taking a look into this now

**Comment by flynnduism** [comment]
@elsmorian the changes are live onsite now. Thanks for flagging this!

https://helm.sh/docs/chart_best_practices/#the-chart-best-practices-guide
