### ISSUE TITLE
[docs] restructure to support versioning

### ISSUE THREAD

**Issue by flynnduism** [helm/helm-www#198]
Since Helm 2, the docs site has just shown the latest state of the project docs. Ideally we should restructure things with Helm 3 on the horizon:

* render different versions of the site so there is a clear url structure
  e.g. `helm.sh/2.13.1/` and `helm.sh/3.1`
* clearly indicate what version of docs you're viewing
* i'll create issues for related tasks with the **v3** label
  * highlight the Helm 2 > Helm 3 FAQs
  * update the site I.A.
  * new landing page

---  

Example: kubernetes.io

![docs-version-example](https://user-images.githubusercontent.com/686194/55747395-00fbc080-59f1-11e9-98c9-3a7f1d726d13.gif)

**Comment by mattfarina** [comment]
How will we handle multi-lingual alongside that? See https://github.com/helm/helm/issues/4103. I'd hoped to get some folks to get this going.

There was also talk of moving to gitbook (recorded at https://github.com/helm/helm/issues/4100). The idea was to use a doc tool that also has some niceties like search.

**Comment by flynnduism** [comment]
It's certainly technically possible. Hugo has a [Multilingual mode](https://gohugo.io/content-management/multilingual/), which in part just means creating additional versions of the site in it's directory structure - which is very similar to methods of versioning we're looking at.

```
helm.sh/fr/
helm.sh/zh/blog/content
helm.sh/us-en/docs/2.13.1/content
```

Doing so at a base level would localized versions of Helm's landing page content as well as docs. The trickiest parts IMO are updating internal links to abide by a new structure and create good fallbacks for content that may or may not exist under a certain language.

I'll open a new issue to track this under `helm-www` and I think there will be parallels with this versioning work. 

Gitbook looks like a robust system and could address many of these structural content issues as we scale up - @bacongobbler we should evaluate this and determine if it fits

**Comment by bacongobbler** [comment]
I started taking a look at localization, but I pulled it out of #199 to prevent scope creep. It seems quite trivial to add localization support though thanks to Hugo.
