### ISSUE TITLE
CLI docs - Option descriptions require side scrolling

### ISSUE THREAD

**Issue by seandilda** [helm/helm-www#233]
When reading the command line docs, the element to describe the options is artificially narrow (lots of whitespace to the left and right), and side scrolling is enabled.

This makes the docs very difficult to understand.  To see what's available for a command like 'helm install', a user has to to constantly scroll left and right.  Aside from slowing down reading, this also makes it easy to lose visual indexing between the description and option name as you can only keep one one the screen at a time.

**Comment by flynnduism** [comment]
Fixed and deployed via #235. Closing this issue.
