### ISSUE TITLE
Make the docs navigation menu auto-inferential

### ISSUE THREAD

**Issue by lucperkins** [helm/helm-www#238]
Right now, the docs menu requires each Markdown file in the documentation to specify a parent menu in the page metadata. With Hugo's [sections](https://gohugo.io/content-management/sections/) feature, this shouldn't be necessary. The navigation templates should be updated to utilize section-based logic rather than menus, thereby eliminating the need for menu metadata.

**Comment by bacongobbler** [comment]
Implemented in the `dev-v3-docs` branch. The content only has to specify an optional `weight` field if they want to be sorted in a different order. By default they're sorted alphabetically.

See [here](https://github.com/helm/helm-www/blob/dev-v3-docs/content/docs/intro/getting_started.md) for a non-weighted example, and [here](https://github.com/helm/helm-www/blob/dev-v3-docs/content/docs/howto/chart_repository_sync_example.md) for a weighted one.

Closing!
