### ISSUE TITLE
Search box does not work

### ISSUE THREAD

**Issue by gtseres** [helm/helm-www#240]
Hello, it seems that the top left search field in [this page](https://helm.sh/docs/) does not work (`Search...` field).

**Comment by bridgetkromhout** [comment]
I'm able to duplicate the problem - on https://helm.sh/docs/  the search box is not clickable. (On https://v3.helm.sh/docs/ it does not exist.)

**Comment by flynnduism** [comment]
The bug with the search form was patched 7/23. Closing off this issue.

---

_Regarding the v3 docs:_ - search is based off of the index of live site data, it's only available on the primary stable version of the Helm site (Helm 2). Helm 3 will not have search functionality until it sees a stable release and we change the search tool to work off of that content index.
