### ISSUE TITLE
[v3 docs] tidy up template layout for categories

### ISSUE THREAD

**Issue by flynnduism** [helm/helm-www#247]
Following template changes in #230, these pages are now using the **homepage template** for each _section_ / _category_, which isn't a good fit. Specific things to address:

- [ ] titles and intro copy are off-center
- [ ] the list of subpages (boxes) are askew
- [ ] the boat animation is overused, would rather just use this on the homepage once

---

Examples:

https://v3.helm.sh/docs/intro/
https://v3.helm.sh/docs/topics/chart_best_practices/

**Comment by bacongobbler** [comment]
addressed in #331
