### ISSUE TITLE
[v3 docs] docs homepage

### ISSUE THREAD

**Issue by flynnduism** [helm/helm-www#249]
Following template changes in #230, the v3.helm.sh/docs landing page needs some work. 

## Layout Fixes

Similar to #247, the page layout needs some visual adjustments. These should be quick wins:

- [ ] align text correctly away from the sidebar
- [ ] the subpages / quicklinks are askew

## Landing Page Content

The [new homepage copy](https://github.com/helm/helm-www/blob/dev-v3-docs/content/docs/_index.md) provides an architectural overview of the docs.

This is a great start. However, there isn't a clear _"getting started"_ / _"how to use helm 3"_ path for users - as we iteratively build on the `dev-v3-docs` we need to map the content out for a friendly UX.

**Comment by hickeyma** [comment]
@flynnduism Also, the "Read the Docs" link goes to v2 docs

**Comment by bacongobbler** [comment]
addressed in #203 

@hickeyma thanks for raising this. I opened https://github.com/helm/helm-www/pull/341 to address that particular issue.
