### ISSUE TITLE
(bug): fix netlify preview inconsistencies

### ISSUE THREAD

**Issue by flynnduism** [helm/helm-www#259]
Netlify previews show `docs/topics/architecture` as the docs homepage, which is very unusual and not inline with how production and dev builds render the site.

It's being doing so for awhile (since we started using the previews), but have worked around it. Filing this issue and will follow up today to address it.

--- 

Context: see [#241](https://github.com/helm/helm-www/pull/241)

**Comment by karuppiah7890** [comment]
issue title is `netflix` instead of `netlify` 😅

**Comment by flynnduism** [comment]
Haha, good spot @karuppiah7890

**Comment by bacongobbler** [comment]
has this been addressed or is it still an issue?
