### ISSUE TITLE
add CODEOWNERS file for blog content

### ISSUE THREAD

**Issue by bacongobbler** [helm/helm-www#278]
It was noted by some of the project maintainers that having permissions to edit a website and having permissions to curate the content of the blog should be differentiated.

Github has a concept called a [CODEOWNERS](https://help.github.com/en/articles/about-code-owners) file, and that workflow has worked out well for the Helm Charts team. Perhaps the blog directory should have a CODEOWNERS file with the core maintainers on there.

**Comment by bridgetkromhout** [comment]
Do we want to follow up at this point with trying to define in CODEOWNERS the people who are allowed to edit the website vs the blog? Or do we think the current LGTM process is covering it? or some other option I haven't outlined? Thanks.

**Comment by bacongobbler** [comment]
I believe the conversation had to do with:

- who can approve/merge certain translations
- who can approve/merge changes to the site theme
- who can approve/merge blog posts
- who can approve/merge changes to the documentation

Maintainers of the helm-www project may be able to fulfill only a few of those roles. For example, I cannot review changes to the Russian locale.

The current LGTM process is covering this fine at the mement. But this is about how we can delegate roles to new maintainers (and possibly encourage others to help join in).

I've received feedback from prospective maintainers coming to Helm that maintaining the entire project seems like a daunting task. I thought splitting into separate, more specialized roles might encourage new maintainers to take on smaller roles.

**Comment by angellk** [comment]
closing as stale, please reopen if this is something you'd still like to see @bacongobbler
