### ISSUE TITLE
Doc navigation broken

### ISSUE THREAD

**Issue by mattfarina** [helm/helm-www#284]
Some of the navigation is broken. It was reported over at https://github.com/helm/helm/issues/6436. If I go back to the docs for v2.14.0 the links appear to work.

**Comment by mmatur** [comment]
@mattfarina 

FYI 

- The current production https://app.netlify.com/sites/helm-merge/deploys/5d7ab2e44264e200092a19c9 does not work https://5d7ab2e44264e200092a19c9--helm-merge.netlify.com/docs/using_helm/#quickstart-guide

- The production deploy just before https://app.netlify.com/sites/helm-merge/deploys/5d79f93d1525cc00086f08da works https://5d79f93d1525cc00086f08da--helm-merge.netlify.com/docs/using_helm/#quickstart-guide

And the only diff between these two versions is https://github.com/helm/helm-www/compare/db61dec9281b997e1b5ad101da55e29615c90f56...8fd5ad21ad39a03e546e834ea465179e5e4e132e

**Comment by flynnduism** [comment]
Thanks for flagging this!

Rebuilding the site has restored the proper site contents (e.g. [Installing Helm](https://helm.sh/docs/using_helm/#installing-helm))

**Comment by bacongobbler** [comment]
Working now. Thanks!
