### ISSUE TITLE
Documentation website not accessible

### ISSUE THREAD

**Issue by nvivo** [helm/helm-www#288]
I'm trying to look at the documentation website, it gives me a HTTP 301 Redirect loop.

I'm just clicking on the "docs" link in the front page, already cleared the cookies and cleared the dns cache.

![image](https://user-images.githubusercontent.com/202449/65534056-2748e600-ded5-11e9-97ad-7fe1ce1f3c66.png)

Header details:
![image](https://user-images.githubusercontent.com/202449/65534331-90305e00-ded5-11e9-90db-c6cdf32a7bae.png)

**Comment by bacongobbler** [comment]
When testing via cURL, there does appear to be a redirect that occurs when the trailing slash is omitted, but then it redirects to /docs/, which resolves with a 200 OK on my end.

```
><> curl -LI https://helm.sh/docs
HTTP/2 301 
cache-control: public, max-age=0, must-revalidate
content-type: text/html; charset=UTF-8
date: Fri, 20 Sep 2019 19:42:10 GMT
etag: "cd3e1e6651f2b043e99bb28af657a7df-ssl"
strict-transport-security: max-age=31536000
age: 337202
content-length: 36531
server: Netlify
x-nf-request-id: c52d6c5a-9e11-49f6-ace5-797ed7506b29-2868229
location: /docs/

HTTP/2 200 
cache-control: public, max-age=0, must-revalidate
content-type: text/html; charset=UTF-8
date: Tue, 24 Sep 2019 17:04:57 GMT
etag: "003c7603e76f616fa775a405aea8bd07-ssl"
strict-transport-security: max-age=31536000
age: 1035
content-length: 36531
server: Netlify
x-nf-request-id: c52d6c5a-9e11-49f6-ace5-797ed7506b29-2868236
```

**Comment by nvivo** [comment]
Just did some tests using a proxy service, if the request comes from US, UK or Spain, it works. Tested from Japan, Canada, Egypt, Brazil and some other countries didn't.

Perharps some CDN cache is outdated?

**Comment by flynnduism** [comment]
Thanks for flagging this. We use netlify but there's no caching service. Looks like they are having some service issues right now.

`https://www.netlify.com/docs/` returns the same `ERR_TOO_MANY_REDIRECTS` issue. Lots of twitter reports of an outage, though [their status page](https://www.netlifystatus.com/) is still all green.

**Comment by nvivo** [comment]
At least it's not just here!

Thanks. I'll use the proxy for now and I'll get from a cache if not accessible.

**Comment by flynnduism** [comment]
@nvivo you can browse the docs files [directly on github here](https://github.com/helm/helm/tree/master/docs) (for latest Helm 2 stable release) or [here for Helm 3](https://github.com/helm/helm-www/tree/dev-v3-docs/content/docs) (beta)

**Comment by flynnduism** [comment]
Netlify networking issue is resolved, the site is back up now!
