### ISSUE TITLE
Helm 3: Docs Home page design

### ISSUE THREAD

**Issue by karuppiah7890** [helm/helm-www#297]
I noticed the home page of v3 docs could get more spacing in terms of design. It's all too compact now

<img width="1440" alt="Screen Shot 2019-10-02 at 10 32 33 AM" src="https://user-images.githubusercontent.com/12808424/66019358-a5724180-e500-11e9-95fa-834896488a47.png">

I think the text on the top should not be so close to the water. Felt it could be better. Probably some CSS issue, not sure what

**Comment by bacongobbler** [comment]
fixed in #331.
