### ISSUE TITLE
Link to securing_installation.md exists in Helm V3 Quickstart but actual document covers tiller

### ISSUE THREAD

**Issue by ecout** [helm/helm-www#298]
This is a duplicate of issue: https://github.com/helm/helm/issues/6507 and has been created as requested by:
@hickeyma 

Output of `helm version`:
v 3.0.0 - beta 1
Output of `kubectl version`:
N/A
Cloud Provider/Platform (AKS, GKE, Minikube etc.): 
AWS

Documentation:
The Quick Start Guide here:
https://v3.helm.sh/docs/intro/quickstart/

has a broken link to this file: securing_installation.md 
https://v3.helm.sh/docs/quickstart/securing_installation.md

Did a lookup for open and closed issues and couldn't find anything filed for this specific link in Helm V3. Among them:
https://github.com/helm/helm/issues/5342

Update: The document linked lies here: https://github.com/helm/helm/blob/master/docs/securing_installation.md

From its content it looks like it shouldn't apply to Helmv3 as it discusses securing tiller a part of the architecture that was removed in v3.

Thanks!

**Comment by bacongobbler** [comment]
thanks @ecout. The documentation for Helm 3 has moved to the helm-www repo under the `dev-v3-docs` branch, so the actual document no longer exists. We probably need to update the quickstart and remove that section.

Here's the Helm 3 docs' new location: https://github.com/helm/helm-www/tree/dev-v3-docs/content/docs

**Comment by bacongobbler** [comment]
The "Securing your Helm Installation" guide was removed from the Helm 3 site, as it went over various knobs for Tiller which no longer exists. https://v3.helm.sh/docs/topics/rbac/ is the only topic guide in Helm 3 that users should be aware of.

Closing.

**Comment by ecout** [comment]
@bacongobbler You're welcome! Thanks for addressing.
