### ISSUE TITLE
installation guide link missing in docs' quickstart

### ISSUE THREAD

**Issue by martinvelos** [helm/helm-www#299]
https://v3.helm.sh/docs/intro/quickstart/#install-helm has missing "the installation guide" link's target. (Install section)
In v2 this went to packaged binaries, which we don't have in v3/beta.

**Comment by bacongobbler** [comment]
transferred to helm-www

**Comment by hickeyma** [comment]
Thanks for transferring @bacongobbler. Didn't realise this could be done.

**Comment by bacongobbler** [comment]
fixed in #339
