### ISSUE TITLE
v3 vanity url for imports

### ISSUE THREAD

**Issue by mattfarina** [helm/helm-www#300]
`import helm.sh/helm` worked until we moved to Go modules and v3. Now we need to have `import helm.sh/helm/v3`. There needs to be an additional redirect put in place for this.

You can read the docs on this stuff at https://github.com/golang/go/wiki/Modules#releasing-modules-v2-or-higher.

**Comment by rimusz** [comment]
@mattfarina can you address this issue ASAP please, we got blocked by this issue with cutting new release for https://github.com/helm/helm-2to3
Thank you
