### ISSUE TITLE
Documentation incorrectly uses hyphens in environment variables

### ISSUE THREAD

**Issue by mac9416** [helm/helm-www#316]
[This page](https://helm.sh/docs/helm/#synopsis) lists environment variables with hyphenated words. I know that at least `TILLER-NAMESPACE` [should use an underscore instead](https://stackoverflow.com/q/58492256/684776).

**Comment by bridgetkromhout** [comment]
The page in question is at https://v2.helm.sh/docs/helm/ now and still has this problem. In the original source it has underscores, and something in the site build is turning them into dashes:

https://github.com/helm/helm/blame/dev-v2/docs/helm/helm.md#L25-L36

**Comment by bridgetkromhout** [comment]
Verified that https://v2.helm.sh/docs/helm/ shows the correct content now.
