### ISSUE TITLE
create v2.helm.sh

### ISSUE THREAD

**Issue by bacongobbler** [helm/helm-www#319]
As part of the 3.0.0 release, we will need to switch the main documentation in helm.sh over to the v3 repository. In the meantime, we should create a CNAME for v2.helm.sh that points to the current documentation for Helm 2, similar to how we have a v3.helm.sh for Helm 3.

**Comment by flynnduism** [comment]
Archival site created here or v2 Latest Docs: https://v2-helm.netlify.com/

Ticket [filed](https://jira.linuxfoundation.org/servicedesk/customer/portal/2/IT-18103) with the LF to create a v2.helm.sh subdomain record.

**Comment by bacongobbler** [comment]
https://v2.helm.sh/
