### ISSUE TITLE
switch dev-v3-docs to master; master to dev-v2-docs

### ISSUE THREAD

**Issue by bacongobbler** [helm/helm-www#322]
As Helm 3 will become the new development branch moving forward, the Helm 3 documentation site should become the new master branch. This will make it easier for new developers who want to contribute documentation, enhancements or blog posts for Helm 3.

**Comment by flynnduism** [comment]
The switch has been made. 🎉 :shipit: 

```
helm.sh        ->  v2.helm.sh
(master)          (dev-v2-docs)

v3.helm.sh     ->  helm.sh
(dev-v3-docs)     (master)
