### ISSUE TITLE
Helm 3 Docs 404 install guide

### ISSUE THREAD

**Issue by dstrebel** [helm/helm-www#326]
Output of `helm version`: Helm 3

Output of `kubectl version`: NA

Cloud Provider/Platform (AKS, GKE, Minikube etc.):  NA

"The installation guide" link on this page https://v3.helm.sh/docs/intro/quickstart/ .  redirects to a 404 page.

**Comment by bacongobbler** [comment]
seems to work now. closing.

**Comment by bacongobbler** [comment]
fixed in #339.
