### ISSUE TITLE
Documentation for .helmignore file is missing

### ISSUE THREAD

**Issue by Tzrlk** [helm/helm-www#328]
The changes applied as part of helm/helm#4638 are no-longer in the online documentation being published from helm/helm-www to https://helm.sh/docs/

**Comment by bacongobbler** [comment]
this is probably because the `template-concat` gulp task does not include the file introduced in that PR. Feel like adding that in there? :)

**Comment by bacongobbler** [comment]
https://github.com/helm/helm-www/blob/e4c8fb0255075ba1da1781ea22d6b7b0620b13a9/gulpfile.js#L96

**Comment by Tzrlk** [comment]
I've done the basic work in a fork, though when running the site locally, I don't see the file included in the page output. Should I create a merge request to discuss the changes?

**Comment by bacongobbler** [comment]
Sure
