### ISSUE TITLE
update contributing info in README.md on helm docs

### ISSUE THREAD

**Issue by dastrobu** [helm/helm-www#342]
Currently the [README.md](https://github.com/helm/helm-www/blob/dev-v3-docs/README.md) states 
> How to Edit The Helm Docs
> Edits to the docs themselves should be carried out via pull requests on the [helm/helm](https://github.com/helm/helm/tree/master/docs) main repo. This site will then extract those files during the build process, and publish them to docs.helm.sh.

Where the link [helm/helm](https://github.com/helm/helm/tree/master/docs) leads to 404. 
It seems to be the case that docs have been moved to the helm-www repo for v3, which should be reflected in the README.md. 

I would like to contribute to the v3 docs, to address issues [6342](https://github.com/helm/helm/issues/6342) and [6343](https://github.com/helm/helm/issues/6343) but contributing to the docs is currently not well documented as well.

**Comment by flynnduism** [comment]
Hi @dastrobu thanks for bringing this to our attention. The readme is incorrect!

The docs for Helm 3 have moved to this repo. They can be found here: [https://github.com/helm/helm-www/tree/dev-v3-docs/content/docs](https://github.com/helm/helm-www/tree/dev-v3-docs/content/docs) on the dev-v3-docs `branch` , which will replace master once Helm 3 is fully released.

I will update the Readme to the new location.
