### ISSUE TITLE
ci for docs.helm.sh

### ISSUE THREAD

**Issue by vdice** [helm/helm-www#35]
We're currently planning on serving the helm docs as a subdomain on the existing `helm.sh` site, that is, at `docs.helm.sh`.

To do so, and hook up CI/CD to do the webpage build/deploy, we'll want to:
 * create a `docs` sub-directory, under which the following will be added:
   * a `rootfs` folder to hold built html/assets/web page
   * a `Dockerfile` which will bundle said assets into an image that can be deployed as a Workflow app
   * a `Makefile` for housing build/deploy targets (such as the one currently used here for helm.sh)

Associated/Infra:
 * Cloudflare subdomain addition
 * add CI (either a `Jenkinsfile` or another job written in DSL in the `deis/jenkins-jobs` repo)

**Comment by slack** [comment]
I think this covers it. Ronan's PR also informs Jekyll to ignore `docs/` so it isn't published along with helm.sh.
