### ISSUE TITLE
[v3] docs search not working

### ISSUE THREAD

**Issue by flynnduism** [helm/helm-www#377]
![Screen Shot 2019-11-12 at 10 24 57 PM](https://user-images.githubusercontent.com/686194/68738484-4857ba00-059b-11ea-87c7-ee05e9ae6b83.png)

The algolia search tool is still rendering on `v2.helm.sh` but not on `helm.sh`.

---

* check the domain config for the search
* see about rebulilding the search index now that the site content + structure has been changed

**Comment by mattfarina** [comment]
Closing as it is rendering and working on both the v2 and v3 docs.
