### ISSUE TITLE
Helm 3 FAQ: Why use Secrets instead of ConfigMaps?

### ISSUE THREAD

**Issue by morremeyer** [helm/helm-www#385]
[The FAQ](https://v3.helm.sh/docs/faq/#secrets-as-the-default-storage-driver) informs us about the default storage driver changing from ConfigMaps to Secrets, but does not provide information as to why.

I couldn't find the "why" so far, so it would be nice if someone knowing about it or being better with their google-foo than I am could add the information.

**Comment by bacongobbler** [comment]
In Helm 2.7.0, a new storage backend that uses Secrets for storing release information was implemented. This was added for additional security in protecting charts in conjunction with the release of Secret encryption in Kubernetes. Encrypting secrets at rest is a feature that has been made available as an alpha feature in Kubernetes 1.7. This allows users to encrypt Helm release metadata at rest, and so it is a good starting point that can be expanded later into using something like Vault.

Hope this helps!

**Comment by bacongobbler** [comment]
https://v2.helm.sh/docs/using_helm/#secret-storage-backend

**Comment by mattfarina** [comment]
The why would be a good think to have under https://helm.sh/docs/faq/ where it talks about the switch to secrets.

**Comment by bridgetkromhout** [comment]
Okay, we've edited the FAQ to clarify this. Thanks, @morremeyer!
