### ISSUE TITLE
Articles are sorted alphabetically, not in conceptual order

### ISSUE THREAD

**Issue by ErinCall** [helm/helm-www#405]
In the docs sidebar, as well as index pages like https://v3.helm.sh/docs/topics/, the articles are sorted alphabetically by title. However, the articles' contents assume a different ordering. 

For example, `content/docs/topics/chart_template_guide/control_structures.md` says "Since we commented out drink: coffee in our last example..." That's referring to an example in `content/docs/topics/chart_template_guide/functions_and_pipelines.md`, which is much later in the alphabetized list. You have to hunt through each page to figure out the intended article order.

**Comment by StephenBrown2** [comment]
Pages can be ordered with the `weight: ` keyword in the top-matter. I've submitted a PR with the weights added to match as best as I could the v2 docs. Could you check to see that the topic article orders for "[Best Practices](https://deploy-preview-407--helm-merge.netlify.com/docs/topics/chart_best_practices/)" and "[Developing Templates](https://deploy-preview-407--helm-merge.netlify.com/docs/topics/chart_template_guide/)" make sense [here](https://deploy-preview-407--helm-merge.netlify.com/docs/)?

**Comment by ErinCall** [comment]
Thanks for jumping on this so quickly!

* Developing Templates looks right. 
* Best Practices seems reasonable, but I only skimmed it since I want to get a handle on the topics first.
* The `.md` files that are directly under `topics/` are still alphabetical. They don't seem to do as much building on previous examples, but it does seem like "Charts" should go before "Chart Tests," for example.

**Comment by bacongobbler** [comment]
Thanks for catching this.

>     * The `.md` files that are directly under `topics/` are still alphabetical. They don't seem to do as much building on previous examples,

Each topic guide should be able to stand on its own, so that should be fine. The "Chart Best Practices" and "Developing Templates" topic guides consist of multiple topic guides so that makes sense they need to be weighted.
