### ISSUE TITLE
`helm install` output not updated for helm v3

### ISSUE THREAD

**Issue by StephenBrown2** [helm/helm-www#408]
I'm going through the docs, specifically [Getting Started](https://helm.sh/docs/intro/getting_started/), and the charts are installed several times with a simple `helm install ./mychart`, with the result being a success and the response starting with
```
NAME: clunky-serval
```
or likewise.

Instead, I get the message:
```
Error: must either provide a name or specify --generate-name
```

and when I specify `--generate-name`, I get something like:
```
NAME: chart-1574726273
```

The docs should probably be updated to reflect that. I can do the PR but wanted to confirm that's expected.

EDIT: I see that there is also not a `RESOURCES` section as noted in the docs, and there is a `TEST SUITE` section, so it looks like the tutorial just needs to be combed over for v3 differences.

**Comment by marckhouzam** [comment]
Yes, I can confirm that with Helm 3 you need to specify the name yourself (`helm install myrelease ./mychart`), or use the `--generate-name` flag.
