### ISSUE TITLE
"Read the Docs" link on https://v2.helm.sh/ leads out of v2 page

### ISSUE THREAD

**Issue by erpel** [helm/helm-www#411]
On https://v2.helm.sh/ scrolling down and clicking the "Read the Docs" link leads to helm v3 documentation.

![image](https://user-images.githubusercontent.com/143569/69728946-be285d80-1125-11ea-9d8a-48dc02bf5629.png)

I would have tried to fix myself but did not manage to find the correct place where the v2 website gets its content from.

**Comment by bridgetkromhout** [comment]
@erpel Thank you again for bringing this to our attention. @mattfarina corrected it in https://github.com/helm/helm-www/pull/464.
