### ISSUE TITLE
Does helm v3 still have the 1MB release storage limit?

### ISSUE THREAD

**Issue by vicaya** [helm/helm-www#421]
We're hitting the release size limit issue (https://github.com/helm/helm/issues/1413 , even after compression!). I wonder if v3 did anything to address the problem.

**Comment by bacongobbler** [comment]
This is a backend issue having to do with etcd's storage limit. Helm 3 won't solve this issue, unfortunately.

**Comment by vicaya** [comment]
Was hoping v3 automatically split the release info into chunks that could fit the kv interface of etcd.
How do we dump and inspect the serialized content of a release?
