### ISSUE TITLE
Helm version selector does not work in the Helm website

### ISSUE THREAD

**Issue by gtseres** [helm/helm-www#429]
In the Helm website, at the top-right of the page, the Helm version is displayed along with a downwards facing arrow, leading the visitor to assume that by clicking it, a dropdown for other Helm versions (e.g. 2) would pop up. This is not the case though (screenshot attached):

![Screenshot 2019-12-10 at 16 29 37](https://user-images.githubusercontent.com/8204987/70538144-49641300-1b6a-11ea-8841-c1d06c153cff.png)

[Example page](https://helm.sh/docs/howto/charts_tips_and_tricks/) where the problem can be seen.

Is this the intended behaviour? If not, what is the purpose of the downwards-facing arrow?

**Comment by flynnduism** [comment]
Hi @gtseres, thanks for filing this issue!

We've just deployed a fix, so [https://helm.sh/docs/](https://helm.sh/docs/) should all be back in working order. Thank you for reporting.

**Comment by gtseres** [comment]
It works as expected now! Thanks a lot!
