### ISSUE TITLE
Does Helm v3 require an explicit list of k8s distros it works with?

### ISSUE THREAD

**Issue by tomkivlin** [helm/helm-www#433]
Or should it just state that any Kubernetes distro that is listed as a [Certified Kubernetes Distribution](https://www.cncf.io/certification/software-conformance/#logos) will work?  
Unless there are additional constraints that need to be in place?  In which case, can we detail those, so new additions to the page can prove their compliance for Helm users.

Affected page: https://github.com/helm/helm-www/blob/master/content/docs/topics/kubernetes_distros.md

I'm happy to raise a PR to delete the page, if that's the approach needed.  Briefly discussed this with a couple of the maintainers at Kubecon NA (can't remember names, sorry!).

**Comment by bacongobbler** [comment]
In general, yes, Helm will work with any certified kubernetes distribution. The page was originally put in place to describe any additional setup that may be required to use Helm with those distributions, or other distributions that have not gone through the CKD process (like k3s, for example).

**Comment by mattfarina** [comment]
I think it would be useful to document, likely at the top of this document, that Helm should work with any conformant version of Kubernetes (whether certified or not).

**Comment by bridgetkromhout** [comment]
I've edited this document based on @mattfarina and @bacongobbler's clarifications. Thanks, @tomkivlin!
