### ISSUE TITLE
Search box does not work for v2.14.0

### ISSUE THREAD

**Issue by gtseres** [helm/helm-www#438]
It seems that the search box is unresponsive in the v2.14.0 [documentation page](https://v2-14-0.helm.sh/docs/).

**Comment by flynnduism** [comment]
Hi @gtseres unfortunately we have to limit the search tool to use on more recent versions.

Each archival version of the site is sandboxed and we can't generate seperete Algolia search accounts/indexes/configs each time.

Best way to search older versions is via a `site:` prefix in your preferred search engine ([example](https://duckduckgo.com/?q=site%3Av2-14-0.helm.sh%2Fdocs%2F+question&t=h_&ia=web)).
