### ISSUE TITLE
Quick start guide does not have correct commands.

### ISSUE THREAD

**Issue by chainhead** [helm/helm-www#443]
**Helm version**

```bash
version.BuildInfo{Version:"v3.0.1", GitCommit:"7c22ef9ce89e0ebeb7125ba2ebf7d421f3e82ffa", GitTreeState:"clean", GoVersion:"go1.13.4"}
```

If we are in `mychart` folder (after `helm create mychart`), then does it imply that the `${PWD}` is in `mychart`? If yes, then the next command to clean up the `templates` folder should be, `rm -rf templates/*.*`. However, this command does not remove the `tests` folder; due to which the subsequent `install` command fails with this message:

```bash
Error: template: mychart/templates/tests/test-connection.yaml:4:12: executing "mychart/templates/tests/test-connection.yaml" at <include "mychart.fullname" .>: error calling include: template: no template "mychart.fullname" associated with template "gotpl"
```

Therefore, the command for clean-up should be executed be in the `templates` folder as `rm -rf *`.

Then, the installation command `helm install ./mychart` fails with `Error: must either provide a name or specify --generate-name` error message. This installation command should be run as `helm install ./mychart --generate-name`.

**Comment by bridgetkromhout** [comment]
Hi, @chainhead! Thanks for pointing out the ambiguity. The installation command was already corrected (by including the generated name); I am correcting the rest of this issue with https://github.com/helm/helm-www/pull/723.
