### ISSUE TITLE
Improve library chart documentation

### ISSUE THREAD

**Issue by hickeyma** [helm/helm-www#469]
Add library chart example describing how to use library chart with an app chart

**Comment by hickeyma** [comment]
I'll push a PR shortly for this.

**Comment by hedgss** [comment]
Perhaps it can help somebody.
Create a named function in the library chart in the templates folder.
The file with the named template must have a name that starts from "_". Extention can be tpl or yaml.
You can choose any name for the named templated.
1. **_test.tpl**
```
{{- define "lib.test.tpl" -}}
# TEST. The comment won't be printed
metadata:
  labels:
    app: test
{{- end -}}
{{- define "lib.test" -}}
{{- template "lib.util.merge" (append . "lib.test.tpl") -}}
{{- end -}}
```
**_utils.tpl**
```
{{- /*
common.util.merge will merge two YAML templates and output the result.
This takes an array of three values:
- the top context
- the template name of the overrides (destination)
- the template name of the base (source)
*/ -}}
{{- define "lib.merge" -}}
{{- $top := first . -}}
{{- $overrides := fromYaml (include (index . 1) $top) | default (dict ) -}}
{{- $tpl := fromYaml (include (index . 2) $top) | default (dict ) -}}
{{- toYaml (merge $overrides $tpl) -}}
{{- end -}}
```
2. In the application chart you can use it in the following way:
```
{{template "lib.test" (list . "test-app")}}
{{- define "test-app" -}}
# HERE YOU CAN PUT VALUES THAT YOU WANT TO CHANGE
{{- end -}}
```

**Comment by hedgss** [comment]
It'd be good also to add best practises.
And I think it'd be good to add a similar example with Lua instead of the go templates.

**Comment by hedgss** [comment]
One more question.
 In my case, a template must generate more than one configuration. The configurations are split by "---".
How can I use a template that generates more than one configuration?
e.g.
```
{{- define "lib.test.tpl" -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: my-config1
data:
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: my-config2
data:
{{- end -}}
{{- define "lib.test" -}}
{{- template "lib.util.merge" (append . "lib.test.tpl") -}}
{{- end -}}

```
If I use "lib.test.tpl" in the same chart ```{{ template "lib.test.tpl" .}}``` it works.
It won't work if I use "lib.test"
It prints only the first one configuration.
How can I use a named template in library chart that generates more than one configuration?

**Comment by GarbageYard** [comment]
@hickeyma : Will really appreciate if the Library Charts docs can be updated. Current docs do provide an idea but i feel it's not complete.

**Comment by bacongobbler** [comment]
If anyone wants to write documentation based on the talk @hickeyma gave at Helm Summit EU, it's recorded here: https://www.youtube.com/watch?v=CuV9QUjUcUA

**Comment by hickeyma** [comment]
@bacongobbler I will try and push PR tomorrow on this. Being distracted lately when trying to get to this.

**Comment by hickeyma** [comment]
Pushed PR #526
