### ISSUE TITLE
Add an index of helm functions with pointers to index of Sprig and Go functions

### ISSUE THREAD

**Issue by jkleckner** [helm/helm-www#489]
It is frustrating to get started with Helm in part due to the lack of an index of functions.

A simple list of the functions introduced in Helm in alphabetical order with a synopsis on one line linked to the detailed description would help newcomers a lot to find out what is there.

Duplicating a few of the important ones from Sprig and Go with links to their definitions would also be nice.

Note that the linked Sprig and Go templates similarly lack a compact list of one line descriptions.

Sprig link:
* https://masterminds.github.io/sprig/
Has an incomplete list of functions by category and if you are looking for concatenate strings, you will have to search around under string functions page which is not sorted alphabetically and not compact.

Go template link:
* https://godoc.org/text/template
This is not too bad as it groups actions and functions into fairly compact form, but could benefit greatly from an alphabetically sorted list of one line descriptions for quick access.

**Comment by mattfarina** [comment]
This would be fantastic to add. I like the idea. We should not expect so many people to know Go templates and sprig functions.

It can start small and contributions are very welcome for this.

**Comment by jkleckner** [comment]
Note this useful template cheat sheet: https://lzone.de/cheat-sheet/Helm+Templates

**Comment by kristinnardal2** [comment]
I would like to point out that there are functions in helm that are not documented at all. I just made an issue about this in the [helm repo](https://github.com/helm/helm/issues/7888) but maybe it belongs here instead.

**Comment by hickeyma** [comment]
Thanks to @kristinnardal2 for raising this in https://github.com/helm/helm/issues/7888. Reproducing here to keep the details in the one issue:

> Helm defines a few functions of its own in pkg/engine/func.go for serializing and deserializing data
https://github.com/helm/helm/blob/b735abe8371359fcf0b37de8014bfafcceb1bcf8/pkg/engine/funcs.go#L50-L57

> I use the `toYaml` function quite a lot but I think the only reason I know that it exists is that the default templates when using `helm create` use this function. The main problem I have is that these functions aren't very discoverable, the only way to know that they exist is to either look through the helm code or see someone else use it.

> I suggest we add documentation about these functions along with the [documentation]( https://helm.sh/docs/howto/charts_tips_and_tricks/#know-your-template-functions) for the include, required and template functions as well as in the chart template guide section about [template functions](https://helm.sh/docs/chart_template_guide/functions_and_pipelines/#helm).

**Comment by mattfarina** [comment]
I'm working on a document with all the functions. It's quite a large list.

**Comment by philomory** [comment]
@mattfarina is there a particular branch I could follow the progress of this one (and possibly contribute to)?

**Comment by bacongobbler** [comment]
I believe we can close this. This has been documented in https://helm.sh/docs/chart_template_guide/function_list/.

**Comment by kristinnardal2** [comment]
I recently saw this on the Helm documentation, thanks for doing this!

**Comment by philomory** [comment]
There's several important functions that are not documented, still; should I open a separate issue for those?

**Comment by jkleckner** [comment]
This is definitely an improvement, thanks.

It would have been nice to have a pure compact alphabetical list of one-liners that point into the more detailed descriptions which would serve as an index.

But definitely an improvement.
