### ISSUE TITLE
Code block styles messed up when running locally

### ISSUE THREAD

**Issue by bagratte** [helm/helm-www#499]
This is what I see on, for example, http://localhost:1313/docs/topics/charts/
![image](https://user-images.githubusercontent.com/11438666/74607720-844b6f80-50f4-11ea-924b-5adbb03ff370.png)
All code blocks look like this on localhost.

For comparison, this is what the corresponding code block looks like on https://helm.sh/docs/topics/charts/
![image](https://user-images.githubusercontent.com/11438666/74607751-ce345580-50f4-11ea-9ec1-9cb82670036b.png)

I just did `yarn install` and `hugo serve`.

**Comment by hickeyma** [comment]
@bacongobbler @mattfarina Do you mind transferring this to helm-www repo?
