### ISSUE TITLE
Document lookup function

### ISSUE THREAD

**Issue by mattfarina** [helm/helm-www#505]
I can't seem to find any docs on it.

**Comment by bacongobbler** [comment]
thanks for opening this. @raffaelespazzoli  are you still interested in doing this? You mentioned you were looking into this as per https://github.com/helm/helm/issues/7473#issuecomment-579043756

**Comment by raffaelespazzoli** [comment]
@bacongobbler yes and apologies for taking a long time. Let me take a stab at it.

**Comment by bacongobbler** [comment]
#564
