### ISSUE TITLE
"Using Helm" docs section not built properly?

### ISSUE THREAD

**Issue by dlapiduz** [helm/helm-www#51]
Browsing to https://docs.helm.sh/using_helm/#quickstart-guide should render the quickstart guide but right now I only see the "Using Helm" subsection of the "Using Helm" section.

I wonder if this is a build issue because running hugo on the docs folder renders the section just fine.
![screen shot 2017-07-07 at 8 53 15 am](https://user-images.githubusercontent.com/4604/27960799-328541be-62f2-11e7-9d68-ca6d2084810b.png)
![screen shot 2017-07-07 at 8 54 23 am](https://user-images.githubusercontent.com/4604/27960798-327deca2-62f2-11e7-91ff-9e519ac2d703.png)

**Comment by flynnduism** [comment]
Yep, looks an issue with the build sequence - part of the build never ran. Thanks for flagging this issue. 

I've a fix on the way asap.

**Comment by flynnduism** [comment]
Fixed and deployed.

That content is accessible again at: [https://docs.helm.sh/using_helm/#quickstart-guide](https://docs.helm.sh/using_helm/#quickstart-guide)
