### ISSUE TITLE
Docs, Introduction, FAQ need "What is Helm?"

### ISSUE THREAD

**Issue by fdavis99** [helm/helm-www#512]
I was pointed at https://helm.sh/docs/ having no idea what Helm is. I couldn't find anything that answers that question. Seems like that should be right at the top!

Could borrow from or reference:
https://helm.sh/
https://boxboat.com/2018/09/19/helm-and-kubernetes-deployments/
https://platform9.com/blog/kubernetes-helm-why-it-matters/
https://hackernoon.com/what-is-helm-and-why-you-should-love-it-74bf3d0aafc

Cheers,
--Franklin

**Comment by mattfarina** [comment]
@fdavis99 This is a great catch. Those of us who work on Helm sometimes forget about all the new folks coming to Kubernetes and Helm who can use some basic explanations.

**Comment by bridgetkromhout** [comment]
Thanks again for your feedback, @fdavis99. We've added links and a short description as suggested, and welcome further input on improving the docs.
