### ISSUE TITLE
`Contribute to Docs` link is broken

### ISSUE THREAD

**Issue by oke-py** [helm/helm-www#530]
`Contribute to Docs` link is broken.
![helm-www](https://user-images.githubusercontent.com/4710215/76164059-104e3580-618f-11ea-9eab-ec660cb7db92.png)

It should probably be `https://github.com/helm/helm-www/tree/master/content/en/docs`.
`/en` might be missing.

**Comment by hickeyma** [comment]
@oke-py Thanks for finding this bug. Would you like to push a fix for it?

**Comment by hickeyma** [comment]
Its looks like @lemonli Had found this issue and had already pushed the PR to fix it. Hope that is ok @oke-py ?

**Comment by oke-py** [comment]
LGTM, thanks.
