### ISSUE TITLE
Chart Template Guide link incorrect

### ISSUE THREAD

**Issue by rooftop90** [helm/helm-www#533]
The Link for Chart Template Guide at the bottom on page https://helm.sh/docs/chart_template_guide/getting_started/ references to the start page (https://helm.sh/docs/) instead to the Chart Template Guide (https://helm.sh/docs/chart_template_guide/)

**Comment by hickeyma** [comment]
@rooftop90 Thanks for finding this error. Would you like to push a PR for it?

**Comment by rooftop90** [comment]
No let someone else fix this. Im not used to contributing to docs :-)
