### ISSUE TITLE
Doc Bug: install.go need extra line for markdown to render properly

### ISSUE THREAD

**Issue by jayrajput** [helm/helm-www#536]
![image](https://user-images.githubusercontent.com/2172309/76404244-2b49c100-63ac-11ea-84e9-73c48279fb8d.png)

Need line between 62 and 63 (similar to between 58 and 60). This is causing the documentation markup to not show the command properly

![image](https://user-images.githubusercontent.com/2172309/76404310-45839f00-63ac-11ea-8390-37aa8c1dc4c1.png)

See how the second command is not seen on it's own line.

I can submit a PR if someone can guide me. It is just a matter of adding an extra line.

**Comment by bacongobbler** [comment]
transferred to helm-www. Feel free to contribute to the documentation to fix this!

https://github.com/helm/helm-www/tree/master/content/en/docs

**Comment by jayrajput** [comment]
Ok. I will go ahead and submit a Pull Request. How do I test this pull request? Are there some automated test which needs to be run? Can you provide some guidance on the same?

**Comment by bacongobbler** [comment]
You can test your changes by using `hugo serve`, which will serve up a local site. More info in the README: https://github.com/helm/helm-www/blob/master/README.md#development

**Comment by jayrajput** [comment]
ok..I am working on it..will send PR today.

**Comment by jayrajput** [comment]
I submitted a pull request against this bug: https://github.com/helm/helm-www/pull/537. Let me know  how I have done and I can make updates based on the feedback. The code is simple, but I am unsure if I have followed all the process. I did signed the commit as suggested in the guideline. I am still new to this, so need guidance/feedback.

**Comment by mattfarina** [comment]
Thanks for fixing this.
