### ISSUE TITLE
Helm documentation hyperlinks are dangling

### ISSUE THREAD

**Issue by seh** [helm/helm-www#54]
From the Helm project's [root _README.md_ file](https://github.com/kubernetes/helm/blob/master/README.md), follow [the link to the Quick Start guide](https://docs.helm.sh/using_helm/#quickstart-guide). We arrive at the intended anchor on the intended page, but from there **several of the hyperlinks in the left sidebar (revealed via the blue-striped "hamburger menu") don't work**.

It looks like they mistakenly include the URL path component "using_helm" when they should not.
- The "Using Helm" link is `https://docs.helm.sh/using_helm/using_helm`, which yields a 404 response.
- The "Helm Commands" link is `https://docs.helm.sh/using_helm/helm`, which yields a 404 response.
- The "Charts" link is `https://docs.helm.sh/using_helm/developing_charts`, which yields a 404 response.
- The "Developing Templates" link is `https://docs.helm.sh/using_helm/chart_template_guide`, which yields a 404 response.
- The "Best Practices" link is `https://docs.helm.sh/chart_best_practices/` which doesn't get a response in a reasonable amount of time. (It came through after a couple of minutes.)
- The "Relate Projects" link is `https://docs.helm.sh/related/` which doesn't get a response in a reasonable amount of time. (It came through after a couple of minutes.)

I'm not sure if this is related to the recent kubernetes/helm#2645.

**Comment by flynnduism** [comment]
Thanks for catching and documenting this issue. 🙌

It looks like the _mobile menu_ is indeed busted as described - the link paths in the _hamburger menu_ need updating, it's fallen out of sync with the desktop version.

**Comment by flynnduism** [comment]
Fix the mobile menu is deploying now to [docs.helm.sh](https://docs.helm.sh/)

**Comment by seh** [comment]
Thank you. It works nicely now, and still looks beautiful.
