### ISSUE TITLE
Go deps is not used anymore.

### ISSUE THREAD

**Issue by lindhe** [helm/helm-www#546]
It says in the install docs that "You must have a working Go environment with dep installed". @bacongobbler kindly informed me that helm 3 does not use dep, but mod (which I guess is included in the recent versions of Go?).

https://github.com/helm/helm-www/blob/master/content/en/docs/intro/install.md

**Comment by hickeyma** [comment]
@lindhe Thanks for raising. Would you like to push a fix for this?

**Comment by mattfarina** [comment]
#532 was just merged which fixes this problem. Thanks for catching it. I'm glad to know people are reading the docs.
