### ISSUE TITLE
next button in every page

### ISSUE THREAD

**Issue by yardenfi** [helm/helm-www#553]
Hi,
Moving from one page in the docs to the next is very frustrating.
I'm missing two things:
  1. A link in the end of each page directing me to the next page.
  2. A sidebar that can lead to any page. The current sidebar only covers groups of topics and not specific ones.

**Comment by mattfarina** [comment]
@yardenfi Thanks for the enhancement suggestion.

I think many of us who write the docs and know Helm tend to use it for reference. We can easily forget that folks want to read through the docs as they learn.

**Comment by bridgetkromhout** [comment]
Thanks, @yardenfi. We've added in-section links at the bottom of each page, which should help here. We welcome additional feedback.
