### ISSUE TITLE
intro jumps from `helm search hub` to `helm repo add`

### ISSUE THREAD

**Issue by SimonHeimberg** [helm/helm-www#555]
> The official docs show no explanation how to get from helm search repo which shows hub.helm.sh to helm repo add which magically shows the a new url to use. There is no suggestion of how to find the new urls since search shows hub.helm.sh

from https://github.com/helm/hub/issues/208#issuecomment-573624005

I guess, currently the only way to find the repo of a chart is to go to https://hub.helm.sh (until https://github.com/helm/helm/issues/7419 is fixed). If I am right, please mention it in the intro.

file to fix: content/en/docs/intro/using_helm.md

**Comment by mattfarina** [comment]
@SimonHeimberg thanks for catching this. we can definitely make the documentation a little better.

**Comment by SimonHeimberg** [comment]
I just learnt in https://github.com/helm/helm/issues/7419#issuecomment-609873222 what the url in the output of `helm search hub` is for.  The file `content/docs/helm/helm_search_hub.md` could mention this.
It is mentioned in content/docs/intro/using_helm.md, I found it now when I knew what to search for.
