### ISSUE TITLE
documentation not found

### ISSUE THREAD

**Issue by niteshagrawalgmail** [helm/helm-www#578]
https://helm.sh/docs/developing_charts/#charts-and-versioning gives 404.

**Comment by hickeyma** [comment]
@niteshagrawalgmail The links used in the previous documentation don't necessarily still apply. A lot of re-organization of the docs have occurred. The link you are looking for is now: https://helm.sh/docs/topics/charts/#charts-and-versioning

**Comment by hickeyma** [comment]
Closing as answered.

**Comment by hickeyma** [comment]
It is worth doing a walk through the [docs](https://helm.sh/docs) to familiarise yourself with the new layout.
