### ISSUE TITLE
Doc link issues

### ISSUE THREAD

**Issue by mattfarina** [helm/helm-www#60]
In the docs under the helm ["see also" section the links are to anchors with an `_` in them](https://docs.helm.sh/helm/#see-also). The actual anchors use a `-` (dash) instead ([see example](https://docs.helm.sh/helm/#helm-rollback)). So, the links don't work.

**Comment by bacongobbler** [comment]
I think this is actually a bug in the manpages as noted in https://github.com/kubernetes/helm/issues/2840. We should be able to fix it upstream, which then docs.helm.sh should get that fix :)

**Comment by bacongobbler** [comment]
This turns out to be a bug with spf13/cobra hardcoding the docs generation links as underscores. I'll see if I can fix that.
