### ISSUE TITLE
`helm install` & `helm status` output example is output of Helm 2

### ISSUE THREAD

**Issue by oke-py** [helm/helm-www#628]
`helm install happy-panda stable/mariadb` & `helm status happy-panda` output is old.
The output example should be updated.
https://helm.sh/docs/intro/using_helm/

Helm 2 shows RESOURCES.
```
$ helm2 install -n happy-panda stable/mariadb
NAME:   happy-panda
LAST DEPLOYED: Fri May  8 17:54:10 2020
NAMESPACE: default
STATUS: DEPLOYED

RESOURCES:
==> v1/ConfigMap
NAME                        DATA  AGE
happy-panda-mariadb-master  1     1s
happy-panda-mariadb-slave   1     1s
happy-panda-mariadb-tests   1     1s

==> v1/Pod(related)
...
```

Helm 3 does not show RESOURCES.
```
helm install happy-panda stable/mariadb
WARNING: This chart is deprecated
NAME: happy-panda
LAST DEPLOYED: Fri May  8 17:46:49 2020
NAMESPACE: default
STATUS: deployed
REVISION: 1
NOTES:
...
```

**Comment by hickeyma** [comment]
Good catch @oke-py. Would you like to fix it? The PR needs to be done in the docs repo in: https://github.com/helm/helm-www/blob/master/content/en/docs/intro/using_helm.md

@helm/helm-core-maintainers Do you mind transferring this issue over to the docs repo? I don't have the rights to do it.

**Comment by oke-py** [comment]
@hickeyma I opened a PR for this. #630
