### ISSUE TITLE
lookup function not executed if --dry-run specified

### ISSUE THREAD

**Issue by alstolten** [helm/helm-www#635]
Hi folks, 

took me quite a while to figure out that the lookup (`lookup apiVersion, kind, namespace, name`) function as described [here](https://helm.sh/docs/chart_template_guide/functions_and_pipelines/#using-the-lookup-function) seems not to be executed during a `helm install --dry-run`. 

As in that Chapter (and also the ones surrounding)  are describing in good detail all the other concepts I believe it would be worth mentioning that specific behavior.

What do you think?

Best regards,
Alessandro

**Comment by bacongobbler** [comment]
This was intended by design. Connections to the Kubernetes API server is not allowed during a dry run. In other words, `lookup` immediately returns.

See https://github.com/helm/helm/issues/7955 and https://github.com/helm/helm/pull/7969 for more details.

**Comment by bacongobbler** [comment]
PRs welcome to suggest changes to describe the behaviour during a `helm template`, `helm lint` or a `helm install --dry-run`.

**Comment by jgreat** [comment]
The documentation for `lookup` could use a warning that it will return an empty map if you use `--dry-run`.  

I just lost a couple of hours trying to troubleshoot why I wasn't getting objects back in my chart.

**Comment by bacongobbler** [comment]
@jgreat sorry for the trouble. That's a great suggestion. Would you like to contribute that to the documentation? It's available here if you'd like to suggest any edits to the docs:

https://github.com/helm/helm-www/blob/master/content/en/docs/chart_template_guide/functions_and_pipelines.md#using-the-lookup-function

**Comment by alstolten** [comment]
I gave it a try in #649.

**Comment by alstolten** [comment]
Just saw that @jgreat already did some work. Sorry for that, I did not mean to interfere.

**Comment by ksa-real** [comment]
Is there a reason why `helm install --dry-run` has this by design? I mean if chart generation depends on lookup function then we would like to get a chart that is as close as possible to the one to be applied without `--dry-run`. Particularly, a CR or a secret in K8s may be retrieved and used for manifest generation during helm install.
