### ISSUE TITLE
Chinese(ZH) translation

### ISSUE THREAD

**Issue by zhangqx2010** [helm/helm-www#643]
Suggestions for ZH translation:  

1. one issue for one document, issue/pr title: [ZH] /path/to/file, when ready to pick one doc, create an issue first.
2. Before you pick one for translation, check issues to avoid duplicated work.
3. Please create PR after finishing translation within one week. If one issue created without PR within one week. Others can pickup and translate instead.
4. Preserve origin english for easier review and further update comparison. Just comment out in the translation page.

We may set up a group for reviewing, and can be @ when pr submitted .
@zgfh @bei612 @lucperkins @bacongobbler please add your thoughts.

**Comment by zgfh** [comment]
lgtm

**Comment by zhangqx2010** [comment]
Some conventions needs to be defined so that translation will be uniformed throughout the whole site. Also others like what words should not be translated etc.

**Comment by bridgetkromhout** [comment]
This issue doesn't seem to need further action; thanks!
