### ISSUE TITLE
Link to 'Helm Upgrade' is missing in navigation

### ISSUE THREAD

**Issue by dejfh** [helm/helm-www#644]
Navigation is missing `Helm Upgrade`. I would have expected it between `Helm Uninstall` and `Helm Verify`:
![image](https://user-images.githubusercontent.com/5569332/82338558-56c0db80-99ed-11ea-8c0a-bde2fa6dfcd3.png)

**Comment by bridgetkromhout** [comment]
Hi, @dejfh - I navigated to https://helm.sh/docs/ and clicked "Helm Commands" in the left sidebar, and then scrolled down inside the sidebar. I am able to see the expected output:

![image](https://user-images.githubusercontent.com/2104453/84176325-d2d79d80-aa46-11ea-8548-020838e7310a.png)

Can you let me know what path you followed to find the menu with the missing item? That might allow us to reproduce and then fix this issue. Thanks.

**Comment by bacongobbler** [comment]
this was fixed in #669.
