### ISSUE TITLE
404 Error

### ISSUE THREAD

**Issue by agamezg** [helm/helm-www#658]
trying to navigate from [this tutorial](https://dzone.com/articles/configuring-java-apps-with-kubernetes-configmaps-a) to this link -> https://helm.sh/docs/developing_charts/ and it throw me a 404 respose

**Comment by flynnduism** [comment]
Thanks for reporting @agamezg. 

The tutorial was written for Helm v2. The url structures changed when Helm 3 launched in late 2019. The document that throws that 404 can be found here:

[https://v2.helm.sh/docs/developing_charts/ ](https://v2.helm.sh/docs/developing_charts/)

---  

I will look at adding a redirect rule to the site to avoid more people hitting 404s.

**Comment by bridgetkromhout** [comment]
I was wrong to assert that https://github.com/helm/helm-www/pull/698 would entirely solve this - we need the redirection to go to the v2 link: https://v2.helm.sh/docs/developing_charts/ - @flynnduism, can you address that case too? Thanks!

**Comment by bridgetkromhout** [comment]
Thanks for your feedback, @agamezg - we've now fixed this and related issues.

**Comment by agamezg** [comment]
Your welcome, good to know it was useful
