### ISSUE TITLE
The "Need Helm?" link on chart pages is a 404.

### ISSUE THREAD

**Issue by Asday** [helm/helm-www#670]
https://hub.helm.sh/charts/weblate/weblate/0.1.8, in the install pane on the right, at the bottom.  The link goes to `https://github.com/helm/helm/blob/master/docs/quickstart.md`, which is a 404.

**Comment by bacongobbler** [comment]
Hi there! This repository is for the helm website, helm.sh. Can you please open a ticket over at https://github.com/helm/hub? Thank you!

Closing

**Comment by Asday** [comment]
Appreciated - I don't know the repos so well it seems.  :)
