### ISSUE TITLE
Clear up ambiguity in release checklist

### ISSUE THREAD

**Issue by mattfarina** [helm/helm-www#675]
The release checklist is not clear and has some issues. If you are familiar with it you skip around. If you aren't  familiar with it the flow is difficult to follow. We should break the documentation up into a few sections.

1. Prerequisites one needs to release
2. Major/minor releases
3. Patch releases

The two sections on each type of release should document the complete flow.

**Comment by bridgetkromhout** [comment]
Now that we document version support info in the docs (https://helm.sh/docs/topics/version_skew/) we should add a step for updating https://github.com/helm/helm-www/blob/master/content/en/docs/topics/version_skew.md in the case of major & minor releases.

**Comment by bridgetkromhout** [comment]
The release checklist should also include a version bump for the relevant section of the website config, like in https://github.com/helm/helm-www/pull/676.

**Comment by bridgetkromhout** [comment]
When I tried breaking the patch release process into its own section, I found I was duplicating a lot of content between the major/minor section and the patch section.

So instead, I tried to label sections more clearly in https://github.com/helm/helm-www/pull/749/ and make it more obvious what path to follow.

Input welcome.

**Comment by bridgetkromhout** [comment]
Hi, @mattfarina - checking in with you, as you opened this issue; do we have additional ambiguity in https://helm.sh/docs/community/release_checklist/ that you'd like to address? Or are we at a place where we can resolve this issue? Thanks.

**Comment by bridgetkromhout** [comment]
As we've changed the release checklist significantly, and run through it several times now, I'm going to resolve this issue. Please re-open with more detail, @mattfarina, if you see more work to be done on the release checklist. Thanks!

**Comment by ReSearchITEng** [comment]
Hi,
while the doc has been updated, we see that the version_skew update step is still not enforced at release time.
