### ISSUE TITLE
investigate build failure

### ISSUE THREAD

**Issue by bridgetkromhout** [helm/helm-www#704]
I asked @flynnduism why https://deploy-preview-702--helm-merge.netlify.app/docs/ had the correct versions in the dropdown while they were not yet updated in https://helm.sh/docs/. He found an issue with Netlify where the previews and production builds differ, leading to the possibility of successful previews and then failed production builds. He will investigate.

**Comment by mattfarina** [comment]
I found that there is a difference between building a preview and for production. On preview `make build-preview` is run and for master/production it's `make build`. For former works on the tip of master while the latter does not.

**Comment by mattfarina** [comment]
Continuing my investigation... it appears that `hugo serve` works as well. There is something different internally going on in the way it handles URLs. I've not looked at the hugo source.
