### ISSUE TITLE
Add the Terraform Helm provider to docs/community/related/#additional-tools

### ISSUE THREAD

**Issue by Redeux** [helm/helm-www#709]
I'd like to add the [Terraform Helm provider](https://github.com/hashicorp/terraform-provider-helm) to docs/community/related/#additional-tools.  I'm happy to submit a PR to add it, but I'd like to make sure it's welcome before doing that.  Thanks!

**Comment by bacongobbler** [comment]
yes! That page is dedicated for promoting third party tools like the terraform helm provider.

**Comment by bridgetkromhout** [comment]
Hi, @Redeux - please do go ahead and open a PR! Thanks.
