### ISSUE TITLE
Helm init documentation missing

### ISSUE THREAD

**Issue by thefreeeman** [helm/helm-www#726]
Documentation is missing:
https://helm.sh/docs/helm/helm_init/

**Comment by thefreeeman** [comment]
Apparently the documentation has been removed, so closing this issue. 
https://github.com/helm/helm/issues/6996#issuecomment-582066606

**Comment by hickeyma** [comment]
FYI @thefreeeman, `helm init` does not exist in Helm 3. This is because you don’t need to install Tiller in the cluster and set up a Helm state before using Helm. 

v2 docs: https://v2.helm.sh/docs/helm/#helm-init
