### ISSUE TITLE
standardize on console instead of shell

### ISSUE THREAD

**Issue by bridgetkromhout** [helm/helm-www#738]
As discussed in https://github.com/helm/helm-www/pull/732#discussion_r448437222, we propose standardizing on "shell" instead of "console" throughout the docs. This is a minor change for consistency and should not materially affect display.

**Comment by bridgetkromhout** [comment]
After looking more at the docs, I begin to think it would be clearer and less confusing for the reader if they see a `$` everywhere they're expected to type something. This means we'd want to use "console".

Example: 
```console
$ helm repo update              # Make sure we get the latest list of charts
$ helm install stable/mysql --generate-name
Released smiling-penguin
```

Using "shell" gives less-formatted output on github:

```shell
$ helm repo update              # Make sure we get the latest list of charts
$ helm install stable/mysql --generate-name
Released smiling-penguin
```

GitHub renders this differently than we do on the website: https://github.com/helm/helm-www/blob/master/content/en/docs/intro/quickstart.md#install-an-example-chart vs https://helm.sh/docs/intro/quickstart/#install-an-example-chart

Another issue is that if we use "shell" with markdownlint, then all the `$` entries will be flagged as an error. As there is no display difference between the two on the website, but we risk making the docs more confusing with the "shell" option and also lose some formatting on GithHub, I'm now thinking we should instead use "console" in all cases (and add the `$` where missing). Input welcome.

**Comment by bridgetkromhout** [comment]
When @mattfarina is available it would be good to get his input here.

**Comment by hickeyma** [comment]
My experience with markdown is console and `$`.  For example:

```console
$ helm list -n test
NAME           NAMESPACE REVISION  UPDATED                                 STATUS    CHART            APP VERSION
[....]
```

**Comment by bacongobbler** [comment]
For some historical reference...

The triple backtick convention was not a Markdown standard at first. Github expanded upon the Markdown spec and introduced the triple backtick for github comments to embed console output in a comment. This was commonly referred to as "Github-flavoured markdown".

Their convention was

```
```console
```

For shell sessions.

`shell` was introduced for shell scripts. If you're trying to fence a shell script, you should use `shell`.

Consider the syntax highlighting output between the two shell sessions here:

shell:

```shell
$ helm list --namespace=test    # a comment
NAME           NAMESPACE REVISION  UPDATED                                 STATUS    CHART            APP VERSION
[....]
```

console:

```console
$ helm list --namespace=test    # a comment
NAME           NAMESPACE REVISION  UPDATED                                 STATUS    CHART            APP VERSION
[....]
```

And consider the syntax highlighting between the two shell scripts:

shell:

```shell
#!/bin/bash
set -eo pipefail

echo $1

for i in 1 2 3 4 5
do
 echo $i
done
```

console:

```console
#!/bin/bash
set -eo pipefail

echo $1

for i in 1 2 3 4 5
do
 echo $i
done
```

The long and the short here is that each type has its own purpose: `console` should be used for terminal sessions (which we use frequently in the docs), and `shell` for shell scripts (less frequent, but still present in several locations).

**Comment by hickeyma** [comment]
I agree, horses for courses @bacongobbler. For example, `yaml` for yaml and `shell` for scripts.

I thought @bridgetkromhout is looking at standard format for commands here but maybe I read it wrong.

**Comment by bridgetkromhout** [comment]
Thanks, @bacongobbler. I have changed examples taking place in terminal sessions from `shell` to `console` in this PR; I think that is in line with the info you're providing. I am not sure if I saw any shell scripts in my perusal of the docs.

**Comment by bridgetkromhout** [comment]
I'm closing this issue because of the differences in Hugo vs GitHub markdown's display pointed out by @mattfarina - more details in https://github.com/helm/helm-www/pull/744#issuecomment-692389360.
