### ISSUE TITLE
Link to test docs becomes Japanese

### ISSUE THREAD

**Issue by lindhe** [helm/helm-www#773]
For me, the "[(view test docs)](https://helm.sh/docs/chart_tests/)" link on [this page](https://helm.sh/docs/topics/charts_hooks/#the-available-hooks) leads me to the [Japanese page](https://helm.sh/ja/docs/topics/chart_tests/) instead of the [English page](https://helm.sh/docs/topics/chart_tests/).

But it seems fine in the markdown...

https://github.com/helm/helm-www/blob/4395c5f74cbde4853922551045ba406a76e302b6/content/en/docs/topics/charts_hooks.md#L35

**Comment by mattfarina** [comment]
Good catch, thanks.
