### ISSUE TITLE
Scrolling the docs is not a pleasant stroll

### ISSUE THREAD

**Issue by thochra** [helm/helm-www#81]
Hello,

I have been using the docs website for only few hours and there is something that is going to make me crazy => scrolling the docs is a nightmare !!!

I don't know why but:
 - after a while or when reaching a specific page's position scroll is blocked and then after some mouse wheel rotations it works again. That behaviour is just ugly. I feel like someone tied up my two shoes' shoelaces together. (or like this http://gph.is/1Sie7un)
 - can't use arrows or page up/down for scrolling (at least firefox linux, chrome seems ok with that)

Hope you'll be able to do something for that :pray:

Thanks in advance,
Thomas

**Comment by flynnduism** [comment]
Thanks @thochra for the flagging. Scroll-jacking is definetly not the intent here.

The docs site uses a [scroll-to-anchor script](https://github.com/helm/helm-www/blob/master/docs.helm.sh/themes/helmdocs/static/src/js/custom/app_init.js#L61L74) that could be causing lag, I can easily remove that to ensure cleaner scrolling. 

Checking the up and down arrows on Firefox OSX, I see the same issue there too. The page frame is rendering in some way that is breaking this, I will investigate further and fix.

**Comment by brendanstennett** [comment]
+1 on this.  It's a very janky scroll experience.  A fixed header would be better than this is.

**Comment by lukejpreston** [comment]
This is still an open issue even though there has been a merge request. Scroll sounds like it is better but still annoying. You wanna perhaps change this line

https://github.com/helm/helm-www/blob/26746b44db347408028474e89a675ee9c107a5b4/docs.helm.sh/themes/helmdocs/static/src/sass/docs-layout.scss#L34

You should just remove it and the website will be fine. I checked it on both mobile and desktop and I couldn't find an example page which had an issue after removing this line. I also changed it to `auto` and never saw a needless scrollbar intercepting my scrolling.
