### ISSUE TITLE
Content-Type issues on root

### ISSUE THREAD

**Issue by flynnduism** [helm/helm-www#82]
Following on from [#3940](https://github.com/kubernetes/helm/issues/3940), there's an issue with styles not rendering on the domain root `https://helm.sh`. They work fine via `www.helm.sh` oddly.

---

# *helm.sh -> www.helm.sh

I'd tried forwarding everything via `www` to circumvent this issue, but that routing isn't working. I've rolled back the DNS as a result. 

---

# Content-Type

@technosophos do you know if the `brigade.js` CI script assigns a `Content-Type` on upload?

I don't see any in the script, but it may be set on the CDN. Some useful notes in this [blog post](https://blog.lifeishao.com/2017/05/24/serving-your-static-sites-with-azure-blob-and-cdn#2-uploading-your-site-with-the-correct-content-type) about the Content-Type defaults, which ideally would be:

* assign `text/html` to the root index.html
* assign `text/css` to the assets/css/* dir

**Comment by bacongobbler** [comment]
az storage upload-batch auto-detects the MIME type when uploading, but perhaps it treated CSS files differently. I can take a look into this
