### ISSUE TITLE
Add untranslated copies

### ISSUE THREAD

**Issue by markruler** [helm/helm-www#829]
> [community/localization.md](https://github.com/helm/helm-www/blame/master/content/en/docs/community/localization.md#L100-L103)

```markdown
Do not add an untranslated copy of an English file to `content/[LANG]/`.
Once a language exists on the site, any untranslated pages will redirect to
English automatically. Translation takes time, and you always want to be
translating the most current version of the docs, not an outdated fork.
```

If someone doesn't add a copy, there is inconvenience because they keep changing languages to read documents through "Quicklinks". I think the UI should be changed or someone should add untranslated copies.

![tg_image_722502575](https://user-images.githubusercontent.com/38225900/93406710-4fdaa480-f8cb-11ea-8d6a-b0e1b349bde8.jpeg)
![tg_image_2070649359](https://user-images.githubusercontent.com/38225900/93406724-5bc66680-f8cb-11ea-9569-caa4e031839f.jpeg)

**Comment by bridgetkromhout** [comment]
What most people have been doing is adding a page when needed for links, and translating the headers on that page. This is better than adding dozens or hundreds of pages at once. Does that make sense?
