### ISSUE TITLE
Translate docs/faq/ into Japanese

### ISSUE THREAD

**Issue by shuuji3** [helm/helm-www#843]
Currently, the following FAQ page has not been translated:

- [Frequently Asked Questions | Helm | Docs](https://helm.sh/docs/faq/)

Since this page has not been translated, the link to this page is not shown on the side menu and Japanese users cannot notice the existence of this page now. This should be fixed soon to help users understand Helm 3.

**Comment by shuuji3** [comment]
At first, I've translated only section headers and a few short sections by #845.

Please use this issue as an umbrella issue for Japanese translation for the FAQ page. Create a new issue and/or PR for new translation of some sections and link it to this issue.

## Sections to be translated

- [x] Headers (#845)
- [ ] Helm 2 からの変更点
  - [ ] Tiller の削除
  - [ ] アップグレード戦略の改善: 3方向戦略的マージパッチ (3-way Strategic Merge Patches)
  - [ ] リリース名が名前空間でスコープされるようになった
  - [ ] Secret がデフォルトのストレージドライバーになった
  - [ ] Go の import path の変更
  - [x] Capabilities (#844)
  - [ ] チャートの Values の JSONSchema による検証
  - [ ] `requirements.yaml` の `Chart.yaml` への統合
  - [x] Name (または --generate-name) がインストール時に必須となった (#845)
  - [ ] チャートを OCI レジストリに push する
  - [ ] `helm serve` の廃止
  - [ ] ライブラリチャートのサポート
  - [ ] Chart.yaml apiVersion のバージョンアップ
  - [ ] XDG のベースディレクトリのサポート
  - [ ] CLI コマンドの名前変更
  - [ ] 名前空間の自動生成
  - [ ] .Chart.ApiVersion に何が起こりましたか？
- [ ] インストール
  - [ ] Fedora などの Linux ディストリビューション向けの Helm のネイティブパッケージが存在しないのはなぜですか？
  - [ ] なぜ `curl ...|bash` で実行するスクリプトを提供しているのですか？
  - [ ] Helm クライアントのファイルをデフォルト以外の場所に配置するにはどうすればいいですか？
- [ ] アンインストール
  - [ ] ローカルの Helm を削除したいです。Helm の全ファイルはどこにありますか？ 
- [ ] トラブルシューティング
  - [ ] GKE (Google Container Engine) 上で "No SSH tunnels currently open" というメッセージが表示されました
  - [ ] Helm 2 からのマイグレーション後、`helm list` リリースの一部 (または全部) が表示されません
  - [ ] macOS 上で `/etc/.mdns_debug` というファイルへのアクセスがあります。なぜですか？
  - [ ] 以前は動作していた helm repo add が失敗する

**Comment by bridgetkromhout** [comment]
Thanks for getting us started, @shuuji3! At this point if anyone wants to submit more translations, we welcome that. Thanks.
