### ISSUE TITLE
Translate community/localization/ into Japanese

### ISSUE THREAD

**Issue by shuuji3** [helm/helm-www#846]
The following page has not been translated into Japanese.

- [Helm | Localizing Helm Documentation](https://helm.sh/docs/community/localization/)

This is an important entry point to the localization of the documentation.

I'm going to translate the page.

**Comment by bridgetkromhout** [comment]
This page has been translated to Japanese: https://github.com/helm/helm-www/pull/920 - please submit additional translations as desired! Thanks.
