### ISSUE TITLE
Helm.sh website using large amounts of CPU

### ISSUE THREAD

**Issue by brendanstennett** [helm/helm-www#85]
Not related to helm specifically but visiting the website causing my CPU to spike and stay there until closing it. It's not just the home page either, other pages seem to have the same problem.

@bacongobbler suggested in https://github.com/kubernetes/helm/issues/3959 that it might be the animations.  I think he might be correct on that one.

It should be considered a high priority issue though because leaving this page open in any browser tab is going to kill a notebook battery in a hurry.

**Comment by bridgetkromhout** [comment]
Is it possible for the boat to (by default) make a trip or two across the page and then pause? Perhaps to be reactivated by a click? (I like watching the boat, but of course I understand we shouldn't over-use people's local resources.)

**Comment by flynnduism** [comment]
@bridgetkromhout we could add some js to stop/pause the animation like you say. Currently there's no JS in play, it's using CSS for keyframe animations. 

**CSS is ~~awesome~~**
Depending on complexity, CSS animation can be pretty [resource heavy](https://www.youtube.com/watch?v=1ZWugkJV5Ks); in this situation it's largely down to how the animation is written with [lots of incremental steps](https://github.com/helm/helm-www/blob/master/themes/helm/static/src/sass/helm-animation.scss#L8L17) - each cycle is actually plotting 10 sub-animations to simulate waves. Plus it's animating along both X and Y axis so it's taxing the browser to calculate a lot of things.

**Simplify things**  
I'd like to make the boat into a bobbing up/down `.gif`, and have than follow a linear path from left to right. I think this would be a quick way to reduce the amount of keyframe animation required of the browser by 90%.

![boat-sm](https://user-images.githubusercontent.com/686194/54379701-1f1b0e80-4647-11e9-9f21-304180d3181c.gif)

e.g. move this along the X axis, elimate the complicated (and incremental) Y axis keyframes.

---

This has been sitting in the issue queue for awhile as I've been prioritizing other items (broken links, infra migration) over it, I must apologize for the neglect.

I will take a look at this today and see how to simplify the CPU demands.

**Comment by flynnduism** [comment]
Closing this following #189
