### ISSUE TITLE
Helm lookup function returns map instead of nil during --dry-run

### ISSUE THREAD

**Issue by rvkamath** [helm/helm-www#863]
Helm Version : v3.2.0
Kubectl Version : Client - "v1.18.0" , Server - "v1.16.8"

I plan to make use of `lookup` function to detect if some resources(like secrets) are present in the cluster before deploying my chart and throw a warning on something missing. 
From a note in doc "Keep in mind that Helm is not supposed to contact the Kubernetes API Server during a helm template or a helm install|update|delete|rollback --dry-run, so the lookup function will return nil in such a case." my understanding is that a lookup in --dry-run will return a `nil`.  However below is my observation

+++++++++++++
Use Case: Handle `lookup` return value differently in --dry-run is to defer throwing a warning to the actual install step.
Command: `kindOf (lookup "v1" "Secret" "ns" "secretname")`
Expected Output : "invalid"
Actual Output: "map"
+++++++++++++

Is the above output expected? If yes, is there another way to achieve the use case. Any help with this is appreciated. Thanks!

**Comment by mattfarina** [comment]
@rvkamath thanks for filing the issue. This is an issue in the docs. An empty map is returned.

Note, I moved this to the repo with the docs so we can address it here.

You can use the `len` function on the response from `lookup` to see if there is any response with the name. Would that work?

**Comment by rvkamath** [comment]
Thanks @mattfarina for fixing the doc.

About the len function on lookup, i checked it returns 0 on --dry-run and also if the object is not found. Is there a way to detect if the helm command execution is a --dry-run? If yes, i can exclude the invocation of lookup in that phase. I checked the built-in objects but could not find anything.
