### ISSUE TITLE
Document that alias do not work

### ISSUE THREAD

**Issue by gajus** [helm/helm-www#872]
It would have saved me an entire day if Helm documentation stated that alias do not work.

A simple note here https://helm.sh/docs/topics/charts/#the-chartyaml-file would do.

For reference: https://github.com/helm/helm/issues/7093#issuecomment-701055080

**Comment by bacongobbler** [comment]
Generally speaking, we do not place information on specific bug reports in the documentation. The maintenance hassle required to PR a "bug report" to the documentation, constantly update it when new information becomes available, then close or remove those admonitions have been known to be difficult to maintain.

The only information we have placed in the documentation related to known issues is in the FAQ. The FAQ is reserved for common error cases with troubleshooting information, or significant changes to Helm (such as any breaking changes in Helm 3). See https://github.com/helm/helm-www/blob/master/content/en/docs/faq/_index.md for more information.

If you find a bug, please report it in the helm issue queue and we can track it there.

Thank you for the report.
