### ISSUE TITLE
Docs: Console error showing up in Chrome

### ISSUE THREAD

**Issue by samirotiv** [helm/helm-www#914]
When I try opening the page located at [https://helm.sh/docs/topics/](https://helm.sh/docs/topics/) using Chrome, I get the error as shown in the screenshot.

Additionally, the page entries do not seem to show up under each section in the left navigation bar.

It seems to work fine in Firefox. I've double checked that there's no interfering plugin - tried in incognito as well. Also tried flushing the site data & cache, and did a hard reset.

In Chrome 86.0.4240.111 on Windows 10 (console trace on RHS):
![image](https://user-images.githubusercontent.com/4405935/97353844-8e944f00-18ba-11eb-8b13-325595b3ac20.png)

In Firefox 82.0.1 on Windows 10:
![image](https://user-images.githubusercontent.com/4405935/97353974-bbe0fd00-18ba-11eb-83a7-ced2dd2adbeb.png)

Best,
Samir.

**Comment by mattfarina** [comment]
Note to those trying to test... I could not reproduce this on Mac. It needs to be tested on Windows as that's where it was experienced.

**Comment by samirotiv** [comment]
Thanks Matt. That's right, just to be sure, I've also tested it from a different computer with an almost-fresh install of Windows. I can also reproduce the same error on the new Microsoft Edge, which is based on Chrome.

**Comment by samirotiv** [comment]
With some digging on the net, I think this may help. 

- [https://jelaniharris.com/2014/fixing-foundation-5s-unrecognized-expression-syntax-error/](https://jelaniharris.com/2014/fixing-foundation-5s-unrecognized-expression-syntax-error/)
- [https://github.com/foundation/foundation-sites/issues/5486](https://github.com/foundation/foundation-sites/issues/5486)
- [https://github.com/foundation/foundation-sites/issues/5593](https://github.com/foundation/foundation-sites/issues/5593)

**Comment by bacongobbler** [comment]
I can confirm that this error also occurs on MS Edge.

**Comment by bacongobbler** [comment]
Looks like the site is using foundation 5.5.3, which does line up with some of the bug reports @samirotiv listed earlier.

https://github.com/helm/helm-www/blob/37fd13eaec7874e2d5e7c5b71738183670c90f89/themes/helm/assets/js/foundation.js#L303

I think the theme is well due for an update on its dependencies.

**Comment by flynnduism** [comment]
The Helm 2 site used the [Foundation 5](https://get.foundation/sites/docs-v5/) framework (css grid, js components like dropdown menus), but for Helm 3 the site was rewritten in [Bulma](https://bulma.io/).

The `foundation.js` should be removed from the site - I'm reviewing the site JS to make sure it's fully removed and that these elements work ok without it:

- [ ] dropdowns (version menu, language menu)
- [ ] offcanvas menu (hamburger menu for mobile browsing)
- [ ] accordions (expanding parent/child links in the left nav) 
- [ ] tooltip (copying install cmd to clipboard)
