### ISSUE TITLE
docs(bug): rbac url in quickstart 404s

### ISSUE THREAD

**Issue by flynnduism** [helm/helm-www#92]
The docs site renders the RBAC section as `https://docs.helm.sh/using_helm/#role-based-access-control`, but there is url in the Quick Start Guide that points to `/rbac`. 

![rbac-404](https://user-images.githubusercontent.com/686194/40804919-8534d8ac-64d1-11e8-8745-51b8822acb82.png)

This works fine when browsing the docs on github.com/kubernetes/helm, but doesn't work on the Hugo rendered version of the docs site here. Thanks to @slack for flagging this.

This is easily remedied via the build pipeline, which runs some find and replace tasks to adapt the markdown files to work with Hugo.

**Comment by bacongobbler** [comment]
closed via #168
