### ISSUE TITLE
feat(architecture): add architecture diagram to docs

### ISSUE THREAD

**Issue by rimusz** [helm/helm-www#96]
What about updating the front page as per:

![helm_sh](https://user-images.githubusercontent.com/5215395/40852910-03439bdc-65c4-11e8-9a48-24fdb8b9babf.png)

it would look better :)
cc @flynnduism

**Comment by mattfarina** [comment]
That image might be good in a section on how Helm works. Someone should re-create it with better coloring and just better.

**Comment by rimusz** [comment]
or there too

**Comment by flynnduism** [comment]
Good call - I'd be happy to adjust the diagram styles and work it into the page.
It could replace this image, which is vague decoration really in comparison:

![https://www.helm.sh/assets/images/chart-illustration.png](https://www.helm.sh/assets/images/chart-illustration.png)

Currently waiting to see what website changes will be required by the CNCF, so holding off on this until that becomes clear.

**Comment by rimusz** [comment]
Yes!!!

**Comment by bridgetkromhout** [comment]
Accurate architectural diagrams are definitely valuable. At this point, given the differences between Helm 2 and Helm 3, we probably want them to be elsewhere than the front page (to prevent confusion). Talking with @flynnduism, he suggested https://helm.sh/docs/architecture/ as a possible location.

**Comment by bacongobbler** [comment]
re-titled the issue to reflect the ask. I agree with @bridgetkromhout and @flynnduism that an architecture diagram in the technical section of the docs makes more sense than the landing page.

**Comment by bridgetkromhout** [comment]
As this issue has remained open for over a year without updates, I'm going to resolve it at this time. @rimusz please do PR in a Helm3 architecture diagram into the docs, if you would like. Thanks for the idea!
