### ISSUE TITLE
Use a helm repo that is not full of deprecated charts as the example

### ISSUE THREAD

**Issue by craiglpeters** [helm/helm-www#965]
It feels strange to point to https://charts.helm.sh/stable in https://helm.sh/docs/intro/quickstart/#initialize-a-helm-chart-repository as it is full of charts marked DEPRECATED. It is confusing to a first time user. Should probably just stick the boring/canonical ngnix-ingress chart example and add https://helm.nginx.com/stable

**Comment by bridgetkromhout** [comment]
Thanks! Many places in the docs need to be updated (this all changed in mid-November).

**Comment by bacongobbler** [comment]
fixed in #1017. When the helm/examples repo is ready, we can replace the current examples with that one. But #1017 removes the deprecation warnings for first-time users so this gets us hobbling along.
