### ISSUE TITLE
[ko] Translate "command/helm_repo" and releated docs" into Korean

### ISSUE THREAD

**Issue by bluefriday** [helm/helm-www#977]
There is no docs about helm repo in Korean

I'll translate follow docs.

helm - command : helm repo
helm - command : helm repo add
helm - command : helm repo index
helm - command : helm repo list 
helm - command : helm repo remove
helm - command : helm repo update

**Comment by bluefriday** [comment]
https://helm.sh/docs/helm/helm_repo/

**Comment by bridgetkromhout** [comment]
Thanks!
