### ISSUE TITLE
[ko] Translate "command/helm_plugin" and releated docs" into Korean

### ISSUE THREAD

**Issue by bluefriday** [helm/helm-www#979]
There is no docs about helm command : helm plugin in Korean

**Comment by bluefriday** [comment]
- https://helm.sh/docs/helm/helm_plugin/
- https://helm.sh/docs/helm/helm_plugin_install/
- https://helm.sh/docs/helm/helm_plugin_list/
- https://helm.sh/docs/helm/helm_plugin_uninstall/
- https://helm.sh/docs/helm/helm_plugin_update/

**Comment by bridgetkromhout** [comment]
Thanks!
