### ISSUE TITLE
[ko] Translate "command/helm_dependency" and releated docs" into Korean

### ISSUE THREAD

**Issue by bluefriday** [helm/helm-www#981]
There is no docs about helm dependency of helm command in Korean

**Comment by bluefriday** [comment]
- https://helm.sh/docs/helm/helm_dependency/
- https://helm.sh/docs/helm/helm_dependency_build/
- https://helm.sh/docs/helm/helm_dependency_list/
- https://helm.sh/docs/helm/helm_dependency_update/

**Comment by bridgetkromhout** [comment]
Thanks!
