### ISSUE TITLE
docs(bug): fix CDN caching issues 

### ISSUE THREAD

**Issue by flynnduism** [helm/helm-www#99]
Seeing problematic caching on the docs site, an incomplete build was deployed.
See the layout [here](https://docs.helm.sh/using_helm/#role-based-access-control).

![40804733-09588be8-64d1-11e8-8113-0f99b465c224](https://user-images.githubusercontent.com/686194/40931024-52d84e9c-67de-11e8-8fba-ccb78db308d9.png)

---

I've tried correcting this and pushing new builds / clearing the cache

* rebuilding the site via the Brigly bot
* manually uploading files to the blob storage
* purging the CDN and endpoint cache (many times!)

---

The correct version of the site is visible in blob storage ([example here](https://helmshprod.blob.core.windows.net/docs-helm-sh/using_helm/index.html?sv=2017-04-17&ss=bqtf&srt=sco&sp=rwdlacup&se=2018-06-05T00:53:43Z&sig=ml3yfiPbFc%2B7VgR9gkQDFRdjuGzhP97dmIYjGmcNBKU%3D) , 'Quickstart Guide' at the top rather than 'Using Helm'), but is not served via the CDN endpoint.

Investigating CDN settings.

---   

Originally tracked this via issue #91 and addressed via PR #98, but the site hasn't updated fully with the fix.

**Comment by bacongobbler** [comment]
Hmm I see it fine from my browser even when squishing the screen horizontally. How can I reproduce this bug?

<img width="829" alt="capture" src="https://user-images.githubusercontent.com/1360539/40932725-271c8a60-67e4-11e8-92ac-722b7db58655.PNG">

**Comment by bacongobbler** [comment]
tested on a burner laptop on edge, firefox, opera and chrome. All seem to work for me so I'm unable to reproduce the bug from my region (Canada).

**Comment by flynnduism** [comment]
Support ticket under way, #118060518322656

**Comment by jaygorrell** [comment]
https://github.com/kubernetes/helm/issues/4155 may be a duplicate.

Also, I can reproduce this if there's anything I can help provide.

**Comment by flynnduism** [comment]
Thanks @jaygorrell 

The issue arose from an incomplete build, a fix was deployed on June 1st; but we've been dealing with caching issues on the site CDN which hasn't been purging and refreshing as expected.

I can no longer reproduce the issue, I'm finally seeing the correct layout rolled out across devices (also testing via VPNs). This should finally be resolved - can you re-test the site today? 

[https://docs.helm.sh/using_helm/#quickstart-guide](https://docs.helm.sh/using_helm/#quickstart-guide)

**Comment by jaygorrell** [comment]
Yep, fixed here as well (after a hard refresh)!
